### ISSUE TITLE
Update filenames for templates and assets to match template (and misc fixes)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#101]
**Matching template names:**

blog-photogallery.amp.html -> article.amp.html
img/blog-photo-gallery/... -> img/article/...

blog-recipe.amp.html -> blog.amp.html
img/blog-recipe/... -> img/blog/...

**Removing "cropped" from img names** 

bird_cropped.png -> bird.png  (same for all of the images — should just have a simple name unless there's a cropped and un-cropped version)

**Make "elephant" plural**
elephant_wide.jpg -> elephants_wide.jpg   (making it plural, like the other one)

**Removing "mojito" language**
themohito.jpg -> spritzer.jpg

BTW: @spacedino — is there a reason we have pngs for some of these, and jpgs for others?

**Comment by tonyruscoe** [comment]
I’ve done this locally and will send a PR soon.
