### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by cramforce** [ampproject/ampstart#115]
- [ ] In sidebar the close X is way too close to the first menu item.
- [x] Logo should be linked to `/`
- [ ] "What is AMP?" leading to a different website is confusing as the first nav point
- [ ] Homepage photos need to be reshot. And need to have HiDPI variant.
- [x] The page templates section on the homepage looks empty on 15" screen.
- [x] UI Components page: The grey boxes look like errors. Maybe switch placeholder.
- [ ] UI Components page: I think people will need more explanation for how to use this. Link to get started?
- [ ] Get started: The images representing the templates need to be linked.
- [ ] Get started: Missing an explanation for how to "deploy" it. Deploy is also a complicated BS word. Maybe "upload to your server or CMS"?

**Comment by cramforce** [comment]
CC @ericlindley-g

**Comment by ericlindley-g** [comment]
Thanks!

I rolled most of these into the current launch-blockers list: https://github.com/ampproject/ampstart/issues/117

I can take a stab at updating the language for UI components explanation and "deploy" BS-replacement :)

Re: "The images representing the templates need to be linked" — do you think they should into the modal preview for the templates themselves, or link back to the section of the landing page featuring the templates?

**Comment by camelburrito** [comment]
@ericlindley-g - is this consolidated in to the Launch blocker ? if so can we close this.

**Comment by ericlindley-g** [comment]
Pending a response from @cramforce on my question, but mostly carried over. Should leave open for now

**Comment by cramforce** [comment]
Re linking: I think both work. Just do something sensible :)

**Comment by ericlindley-g** [comment]
Great — @camelburrito , I think the behavior you had before (where it opens the modal if you click on the template) worked well. Feel free to jump in, @spacedino, as UX owner.

I'll add this to the issues on the homepage (doesn't seem like a launch-blocker to me, but quick and good to fix shortly after — feel free to weigh in on priority, @cramforce ).

**Comment by ericlindley-g** [comment]
All transferred to other issues to track — closing now
