### ISSUE TITLE
The CHECK BOXES  'On' and 'Off' of Form Elements are both enabled

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#116]
Issue: The CHECK BOXES  'On' and 'Off' of Form Elements are both enabled.

Steps to reproduce the bug:
1) Launch Chrome browser
2) Access Url:-https://ampstart-staging.firebaseapp.com 
3) Select UI Components
4) Scroll down for 'Form Elements'
5) Select Check Box1 (On) and Check Box2 (Off)

Observed result: Both the Check Boxes are enabled.
Expected result: only one Check Box can be enabled
Screenshot Attached

![screenshot_2017-02-27-16-06-00](https://cloud.githubusercontent.com/assets/26070187/23387580/59dd6232-fd12-11e6-89f0-23be03cab60e.png)

 ENVIRONMENT DETAILS:
 Browser: Chrome
 Device Model: Galaxy Note 4
 Android Version: 6.0.1

**Comment by camelburrito** [comment]
WAI -
