### ISSUE TITLE
The alignment of the Check boxes is not appropriate

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#118]
Issue: The alignment of the Check boxes is not appropriate
![screenshot_2017-02-27-15-39-59](https://cloud.githubusercontent.com/assets/26070187/23387994/8d674ddc-fd14-11e6-9088-1d2044caa1b8.png)

Steps to reproduce the bug:
1. Launch Chrome browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3. Select UI Components
4. Scroll down for 'Form Elements'

Observed result: 
1. There is no padding for the Check box and the number.
2. Check box 3 is getting truncated.
Expected result: Alignment of the Check boxes has to be appropriate and the Check box should not get truncated.

Environment:-
Browser: Chrome
Device name: Galaxy Note 4
Model No:SM-N910H
Android Version: 6.0.1

Screen shot attached

**Comment by camelburrito** [comment]
Fixed

**Comment by dnukala-corp** [comment]
Observe the same Issue in IOS mobiles :
Environment:-
Browser: Safari and Chrome
Model No: MLXJ2LL/A
Version: 9.3.4


![image 3](https://cloud.githubusercontent.com/assets/26070187/23486152/95ac35d6-fe93-11e6-9920-fe3ad085dd77.png)

**Comment by camelburrito** [comment]
is this iphone 5 ?

**Comment by dnukala-corp** [comment]
Iphone SE

**Comment by dnukala-corp** [comment]
Radio button 3 and Check box 3 are displayed in light grey color.
Environment:
Browser:Chrome
Android version:4.4.4
Mobile:Nexus 4


![image 4](https://cloud.githubusercontent.com/assets/26070187/23489596/42de500e-fea8-11e6-9482-664e4b1da15e.png)
