### ISSUE TITLE
AMP logo is not taking user to homepage

### ISSUE THREAD

**Issue by ansalgado-gcorp** [ampproject/ampstart#129]
Top left corner amp icon does not take user to home page.

![b0omb8qb4os_cropped](https://cloud.githubusercontent.com/assets/22351153/23415420/ffb8bb30-fd93-11e6-970c-856255f10cb4.png)

**Comment by camelburrito** [comment]
The icon is too tiny (you will need to click on the icon) - @spacedino - do you want to make this better

**Comment by camelburrito** [comment]
Fixed
