### ISSUE TITLE
`<link rel="canonical" href="www.ampstart.com">` is a broken link

### ISSUE THREAD

**Issue by tonyruscoe** [ampproject/ampstart#138]
The `<link rel="canonical" href="www.ampstart.com">` tag in amp-page-head.snip.html needs updating so that it either matches the current path or points to the absolute URL including the protocol, i.e. https://www.ampstart.com/

**Comment by camelburrito** [comment]
all of the links should point to themselves (good catch!), can you fix this ?

**Comment by tonyruscoe** [comment]
Is there an easy way to do this or would you suggest just adding a variable for it in the JSON data files?

**Comment by camelburrito** [comment]
yeah variable in JSON would do, there is no easy way. (This has to be the full url.)
