### ISSUE TITLE
The user is unable to select the Checkbox3

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#139]
Issue: The user is unable to select the Checkbox3

Steps to reproduce the bug:
1. Launch Chrome browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3. Select UI Components
4. Scroll down for 'Form Elements'

Observed result: The user is unable to select the Checkbox3
Expected result: The user should be able to select the Checkbox3

Environment:-
Browser: Chrome
Model No: Nexus 6P
![screenshot_2017-02-27-15-39-59](https://cloud.githubusercontent.com/assets/26070187/23443336/fb7afee4-fde2-11e6-8d6e-4e856f850b44.png)

Android Version: 6.0.1

Screen shot attached

**Comment by camelburrito** [comment]
WAI - the checkbox is disabled.
