### ISSUE TITLE
The back button is not working

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#154]
Issue: The back button is not working

Steps to reproduce the bug:
1. Launch Chrome browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3. Scroll down to Page Templates
4. Click 'View Template' in ARTICLE
5. Select 'Read more' 
6. Click Back button

Observed result: The back button is not working
Expected result: The back button should redirect to the previous page

Environment:-
Browser: Chrome
IOS Version: 9.2.1

**Comment by dnukala-corp** [comment]
It is not reproducible.

**Comment by camelburrito** [comment]
even if it is, it would be an AMP Runtime issue.
