### ISSUE TITLE
Options under UI components are not working

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#155]
Steps to reproduce the bug:
1. Launch Chrome browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3. Select UI Components
4. Try Selecting the options :-
             - Disabled Range IP
             - Read  more  
             - Latest Articles (Related Articles )
             - Follow Icon
             - Share Icons               

Observed result : These options are not getting selected.
Actual result : The options should work.

Environment:-
Browser: Chrome
IOS Version: 9.2.1

**Comment by camelburrito** [comment]
WAI
