### ISSUE TITLE
There is an extra text under "READ MORE" which does not have a note,what it is about

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#156]
Issue: 

Steps to reproduce the bug:

1. Launch Safari browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3.Click 'Page Templates'
4.Click 'View Template' in ARTICLE
5. Scroll down to the 'RELATED ARTICLE'

Observed result:There is an extra text under "READ MORE" which does not have a note, what it is about
![image 2](https://cloud.githubusercontent.com/assets/26070187/23484606/838fc02c-fe8c-11e6-9b62-8ff2fe3412fc.png)
.
Expected result: Text need to have a note,which says what it is about.

Environment:-
Browser: Chrome
IOS Version: 9.2.1

**Comment by dnukala-corp** [comment]
Same Issue observed in :
Environment:-
Browser: Safari
IOS Version: 9.2.1

**Comment by camelburrito** [comment]
WAI
