### ISSUE TITLE
The recommendations for the user don't trigger anything

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#158]
Issue: The recommendations for the user don't work

Steps to reproduce the bug:
1. Launch Chrome browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3. Scroll down to Page Templates
4. Click 'View Template' in ARTICLE
5. Scroll down to  'Recommended for you'
6. Click on any recommendations

Observed result: The recommendations for the user don't trigger anything.
Expected result: The recommendations should show the details.

Environment:-
Browser: Chrome 
IOS Version: 9.2.1

Screenshot attached

![image 1](https://cloud.githubusercontent.com/assets/26070187/23485481/60cfbf7a-fe90-11e6-92ca-243568f803a8.png)

**Comment by dnukala-corp** [comment]
The same issue with:
Environment:-
Browser: Chrome
IOS Version: 9.2.1

**Comment by camelburrito** [comment]
WAI
