### ISSUE TITLE
The Follow Icons & 'ABOUT, CONTACT ,TERMS'  take you to the top of the page

### ISSUE THREAD

**Issue by dnukala-corp** [ampproject/ampstart#160]
Issue: The Follow Icons take you to the top of the page
![screenshot_20170228-163641 1](https://cloud.githubusercontent.com/assets/26070187/23487535/9b84c15a-fe9b-11e6-87b9-89d846d1fd9f.png)

Steps to reproduce the bug:
1. Launch Chrome browser
2. Access Url:-https://ampstart-staging.firebaseapp.com
3. Scroll down to Page Templates
4. Click 'View Template' in ARTICLE
5. Scroll down to the end of the page
6.Click on any of the Follow Icons (or) 'ABOUT, CONTACT ,TERMS'

Observed result: It takes you to the top of the page
Expected result: It has to redirect to the page,which the icon shows.
![screenshot_20170228-163641](https://cloud.githubusercontent.com/assets/26070187/23487640/427f1c08-fe9c-11e6-9e75-2782afe154c0.png)

Environment:-
Browser: Chrome
Android Version: 6.0.1
Model no:Nexus 6P

Screenshot attached

**Comment by dnukala-corp** [comment]
The same issue observed in (Mobile)
Environment:-
Browser: Chrome
Android Version: 4.0.1
Model no: Galaxy Nexus

**Comment by camelburrito** [comment]
WAI
