### ISSUE TITLE
Baseline styles should never reference fixed colors

### ISSUE THREAD

**Issue by tonyruscoe** [ampproject/ampstart#163]
Referencing fixed colors in baseline styles means more CSS overrides are needed when themes want to use a different color palette, which not only adds unnecessary CSS but is also more awkward to maintain.

Using byline.css as an example:

```css
.ampstart-byline {
  color: var(--color-dark-grey);
}
```

There are two ways for themes to override the `.ampstart-byline` color, neither of which are particularly desirable:

1. Override `--color-dark-grey` to make it another color
2. Override the color property of the `.ampstart-byline` class in page.css

Instead of `.ampstart-*` classes referencing fixed colors, color variables which have names that reflect their intended purpose (or something more abstract) should be used instead.

I suspect this particular example might have just been an oversight given there are color variables like `--color-font-primary` and `--color-font-secondary` already available, but it should be fixed regardless.

**Comment by camelburrito** [comment]
Correct - Ill update

**Comment by camelburrito** [comment]
Fixed with the typography changes
