### ISSUE TITLE
[All Browsers][All Platforms] Slack link should take user to target="_blank"

### ISSUE THREAD

**Issue by ansalgado-gcorp** [ampproject/ampstart#167]
When user clicks or taps on the footer section, Slack icon specifically, the link opens a Google Forms page.  If user clicks back button, an pop-up window reminder comes up requesting user if he/she agrees to leave.  This link would work better if it was open on a new tab or window.

**Comment by ansalgado-gcorp** [comment]
Small correction, the behavior previously described does not affect iOS(10) Safari.

**Comment by camelburrito** [comment]
We decided against it - https://github.com/ampproject/ampstart/pull/175
