### ISSUE TITLE
[IE10] Layout is broken

### ISSUE THREAD

**Issue by ansalgado-gcorp** [ampproject/ampstart#173]
Rendering on IE10 is broken.  Article Template Preview appears at bottom of page. 

![ie10 - win7-2017-03-02-11-36-28](https://cloud.githubusercontent.com/assets/22351153/23523743/fbb709a6-ff3c-11e6-9651-552681f63a95.png)

**Comment by camelburrito** [comment]
We only support IE 11 and edge
