### ISSUE TITLE
[Android][Tablet][Chrome] Tablet layout mode not showing on portrait mode

### ISSUE THREAD

**Issue by ansalgado-gcorp** [ampproject/ampstart#182]
When tablet is on portrait mode, the tablet button for layout mode does not show.  Please view screenshots for comparison.

![q7fznu8pcht](https://cloud.githubusercontent.com/assets/22351153/23531907/af5907aa-ff5d-11e6-8656-2b99b7f382d9.png)
![rjlq6vsyo7z](https://cloud.githubusercontent.com/assets/22351153/23531918/b0d46d9a-ff5d-11e6-9aa7-a4ca7540a0eb.png)

**Comment by camelburrito** [comment]
WAI
