### ISSUE TITLE
P1 Post Launch  Typography CSS classes

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#188]
@camelburrito @ericlindley-g 

![image](https://cloud.githubusercontent.com/assets/7339798/23534388/74c26bfe-ff6c-11e6-862c-503fc83248e0.png)

**Comment by spacedino** [comment]
we should update the themes as well so that they follow the same / similar pattern

**Comment by ericlindley-g** [comment]
@spacedino, what changes are needed to make this happen in each context (landing page, templates, components, etc)? Is it just sizing, or font, line height, etc, as well?

**Comment by ericlindley-g** [comment]
Also, what's the motivation for this change? — Does it look bad how it is now, or is it a matter of adjusting for consistency?

**Comment by camelburrito** [comment]
Exposing these as classes makes selecting typography easier (via ampstart classes) as opposed to using multiple bass css classes for each type.

It does not look bad now.

**Comment by ericlindley-g** [comment]
Ah, I think I see: is the only work requested in this issue to expose the type styles as classes, rather than using multiple bass css classes for each type? Or are there also changes in the style of the different type styles?

**Comment by camelburrito** [comment]
we would also need to change the usage in the respective templates (not changing would not impact anything - but would set a not so good precedent) and also list it in the components page.

**Comment by spacedino** [comment]
for me this is about setting up a system that includes test styles that are not just applying h classes which map exactly to header tags in terms of size, to p tags. we need to show how you can modify basscss to match what we are using in the baseline templates. we start to do this with .amspstart-subtitle and .caps

right now these are essentially the same styles. we are missing body copy 

![image](https://cloud.githubusercontent.com/assets/7339798/23971661/20883d46-098c-11e7-9d85-97107c8453c2.png)

**Comment by spacedino** [comment]
also i dont thing letter spacing is applied....but i could be wrong.

**Comment by aghassemi** [comment]
5
