### ISSUE TITLE
Template implementation feedback

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#21]
/to @abeck000  to review design feedback
/cc @camelburrito (could you also give me access so I can add assignees and labels?)

intsagram posts could be embedded in main content, rather than tagged on at end (at least fiddle with)

NEWS ARTICLE

- [x] Gap between related articles and footer feels too large

<img width="392" alt="screen shot 2017-02-06 at 5 05 09 pm" src="https://cloud.githubusercontent.com/assets/16807766/22673347/778c3680-ec8e-11e6-960b-0b0ac88d9bf2.png">

- [ ] Sidebar: use n-dashes (e.g. "–") instead of hyphen (e.g. "-") for accordion minimize affordance

- [ ] Use different images in carousel instead of same flower (question: @abeck000, what images are you planning for this template? Is it these?)

- [ ] The hamburger menu icon and close affordance feel a little large

BLOG POST

- [ ] Footer height feels too large
<img width="387" alt="screen shot 2017-02-06 at 5 04 01 pm" src="https://cloud.githubusercontent.com/assets/16807766/22673322/4c9d6584-ec8e-11e6-9fd7-c66547b4f40c.png">

- [ ] Could we use a newsletter signup instead of an inline comment field? I think the way the commenting flow would work with login is like amp-access, where the user is taken to a separate window to sign-in, before coming back to comment, and I don't think we'd want to put something that complex in this template (yet). On the other hand, a newsletter signup is a more straightforward form 

- [ ] Instagram feels a little awkward at the bottom, in practice. May just want to embed in the article body, unless there's a design solution to make it look more at-home

Future enhancement:
- [ ] Caption carrying with image looks awkward — can't fix it now, but can with Bind soon!

**Comment by camelburrito** [comment]
The gap should be reduced now with the SVGs becoming visible. The footer bottom gap is to make sure mobile browser bottom bars do not make content in-accessible.

**Comment by camelburrito** [comment]
@cramforce could you give labels access to @ericlindley-g & @rudygalfi

**Comment by cramforce** [comment]
Done.

**Comment by camelburrito** [comment]
Guess this is old and closing this for now.
