### ISSUE TITLE
Too much space between "Body copy" visual and code snippet

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/ampstart#211]
There's a noticeably large gap between where the end of the "Body copy" visual example ends and where the HTML code snippet starts.

**Comment by ericlindley-g** [comment]
May need a re-design to solve the problem ( @spacedino has that on her radar), but may be work a fix in the meantime

**Comment by ericlindley-g** [comment]
Tracking in https://github.com/ampproject/ampstart/issues/273
