### ISSUE TITLE
disallowed * (universal selector) in template css

### ISSUE THREAD

**Issue by timBrockman** [ampproject/ampstart#243]
`*{box-sizing:border-box}` is being used on line 18 of page-base.css, line 1310 of article.max.css and blog.max.css (as well as in the amp-custom style of both templates).

What do you thing about removing this and explicitly adding it in the classes/elements that need it? It may add a little to the file size, but it is on the verboten list.

It also shows up in `.ampstart-image-heading>*{margin:0}` & `.ampstart-headerbar+amp-sidebar+*{margin-top:3.5rem}`

**Comment by timBrockman** [comment]
I've done some investigating and I think the `*{box-sizing:borde-box}` could be replaced with:
```
amp-sidebar,
div,
section,
input,
textarea,
select,
label,
button,
.btn,
.border,
.border-top,
.border-right,
.border-bottom,
.border-left,
.ampstart-btn,
.ampstart-input {
box-sizing:border-box;
}
```
I ran a build and checked each template visually against `*{box-sizing:border-box}` and it looks ok...
I'm not sure if you want both the likely elements and classes, or if we want both ampstart classes and basscss classes.

I'll start on the other two *s.

**Comment by timBrockman** [comment]
`.ampstart-image-heading > * {margin:0}` replaced with probable headings:

```
.ampstart-image-heading > .h1,
.ampstart-image-heading > .h2,
.ampstart-image-heading > .h3,
.ampstart-image-heading > .h4,
.ampstart-image-heading > .h5,
.ampstart-image-heading > .h6,
.ampstart-image-heading > .ampstart-subtitle,
.ampstart-image-heading > .caps,
.ampstart-image-heading > h1,
.ampstart-image-heading > h2,
.ampstart-image-heading > h3,
.ampstart-image-heading > h4,
.ampstart-image-heading > h5,
.ampstart-image-heading > h6 {
  margin: 0;
}
```
You may want fewer options. The Scenic example only uses h2.

**Comment by timBrockman** [comment]
Replaced:
```
.ampstart-headerbar + *:not(amp-sidebar),
.ampstart-headerbar + amp-sidebar + * {
  margin-top: var(--navbar-height);
}
```
with:
```
.ampstart-headerbar + div,
.ampstart-headerbar + figure,
.ampstart-headerbar + section,
.ampstart-headerbar + article,
.ampstart-headerbar + main,
.ampstart-headerbar + nav,
.ampstart-headerbar + footer,
.ampstart-headerbar + header,
.ampstart-headerbar + amp-sidebar + div,
.ampstart-headerbar + amp-sidebar + figure,
.ampstart-headerbar + amp-sidebar + section,
.ampstart-headerbar + amp-sidebar + article,
.ampstart-headerbar + amp-sidebar + main,
.ampstart-headerbar + amp-sidebar + nav,
.ampstart-headerbar + amp-sidebar + footer,
.ampstart-headerbar + amp-sidebar + header {
  margin-top: var(--navbar-height);
}
```
There is still a layout issue with `.ampstart-headerbar`'s margin top clashing with the main's #content styles in the blog template.

**Comment by ericlindley-g** [comment]
Thanks for addressing this, @timBrockman ! Passing to @camelburrito  for discussion & review of the PRs

**Comment by timBrockman** [comment]
I accidentally dysnomia'd one of the commit messages to reference # 234.

**Comment by timBrockman** [comment]
This could be closed. The docs were updated to reflect the current state of the spec.
