### ISSUE TITLE
Landing page -  make preview header more user friendly

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#250]
- we have a new design for this in the final files folder
- add rollovers - need to work this out with dev
- fix selected state
- update with new icons (black, in final files folder)

**Comment by ericlindley-g** [comment]
Replacing device frame icons is high priority

**Comment by spacedino** [comment]
[mobile_small.svg.zip](https://github.com/ampproject/ampstart/files/849206/mobile_small.svg.zip)
[expand_icon.svg.zip](https://github.com/ampproject/ampstart/files/849208/expand_icon.svg.zip)
[tablet_small.svg.zip](https://github.com/ampproject/ampstart/files/849209/tablet_small.svg.zip)

**Comment by spacedino** [comment]
![image](https://cloud.githubusercontent.com/assets/7339798/24022054/68cbc746-0a61-11e7-9607-97e310adf754.png)
 
![image](https://cloud.githubusercontent.com/assets/7339798/24022060/7667811a-0a61-11e7-9793-84a39ac03c62.png)

![image](https://cloud.githubusercontent.com/assets/7339798/24022067/7d9e5666-0a61-11e7-8174-69e92e148aa3.png)

![image](https://cloud.githubusercontent.com/assets/7339798/24022075/89228c82-0a61-11e7-9a01-b817f8904b65.png)
