### ISSUE TITLE
Components page - Ranged input doesn't appear in chrome mobile emulator

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#258]
<img width="455" alt="screen shot 2017-02-20 at 3 16 13 pm" src="https://cloud.githubusercontent.com/assets/16807766/23144895/9a98c23c-f77f-11e6-9d6f-00c61c860efd.png">

**Comment by camelburrito** [comment]
Seems like an emulator issue, nothing specific to AMP Start (works fine on actual devices)
