### ISSUE TITLE
Navigation - fix X, too big

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#264]
X in sidebar is too big and spacing looks off ( /to @abeck000 to provide specifics — may just want to use smaller image with large tap-target)

**Comment by spacedino** [comment]
@camelburrito and i need to pair on this one.

**Comment by spacedino** [comment]
Ok so i made a new mock up that should work for desktop and mobile. we need to:
[ ] increase the X size on mobile 
[ ] increase the type size to 24px for both
[ ] increase tap target on mobile and desktop to min 40px box around the X, maybe more like 60px
[ ] make sure the X and hamburger menu are left aligned and take up the same size square. Right now they are off.

![image](https://cloud.githubusercontent.com/assets/7339798/24571689/afdf2ad4-1627-11e7-9f58-32a56de6a1fd.png)

![image](https://cloud.githubusercontent.com/assets/7339798/24571707/cbea3106-1627-11e7-92d6-a517be625ecf.png)
 
![image](https://cloud.githubusercontent.com/assets/7339798/24571712/d409b294-1627-11e7-935e-3a4862080d15.png)

i will probably need to work closely with @camelburrito because i still dont quite understand what the problem was with implementation.

**Comment by spacedino** [comment]
assigning back to @ericlindley-g to prioritize

**Comment by camelburrito** [comment]
I think this has been fixed
