### ISSUE TITLE
Sidebar and Footer - external links should open in a new window

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#266]
slack, WP, github, twitter, privacy, license, amp project

**Comment by Lillian-wang** [comment]
@camelburrito , Could you clarify on what I should do in this bug a little? 

1) What does @spacedino mean in his/her commented "slack, WP, github, twitter, privacy, license, amp project"?

2) By sidebar and footer, are you referring to these: components/footer/footer.snip.html and components/navbar/sidebar.snip.html ?

3) Are sidebar and footer reusable components? If so, let me know if the following approach sounds reasonable for implementing the feature: on component initialization,  crawl it's children for anchor tags. For each anchor, check to see if it's domain matches that of the current site. If not, it's an external link, and add " target= '_blank' "

**Comment by camelburrito** [comment]
@Lillian-wang - almost everything under components/ folder is re-usable, however the some of the  contents come from a [json](https://github.com/ampproject/ampstart/blob/master/templates/article.amp.json#L200) config, i think you can add targets here and use it in the components. You will need to make sure this applies to all 4 templates.
