### ISSUE TITLE
Opinionated template 2 - image in hero moved upon scroll on iOS

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#269]
When user scrolls up on iOS, the hero image gets bigger as it moved out of frame.

**Comment by spacedino** [comment]
this is actually happening on the baseline templates as well...this might need looking into and then to be renamed...

**Comment by ericlindley-g** [comment]
Yeah, I think this is captured somewhere else, but not sure — it's an artifact of the image getting its sizing from the viewport height, and the viewport height depending on whether the browser header is displayed or not. Not sure if there's an easy fix, but something to think about (for instance, what behavior do we actually want, if the header is hiding/showing?)
