### ISSUE TITLE
Landing page: Update opinionated template images to not use hipster ipsum

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#276]

**Comment by spacedino** [comment]
![article_baseline_theme copy 7](https://cloud.githubusercontent.com/assets/7339798/24308971/473a2204-1087-11e7-95ac-5cf122540a88.png)
![article_baseline_theme copy 7 2x](https://cloud.githubusercontent.com/assets/7339798/24308970/47397ca0-1087-11e7-9e1d-b60c2e1174f4.png)
![article_baseline_theme copy 8](https://cloud.githubusercontent.com/assets/7339798/24308973/473b7dac-1087-11e7-9b38-b30165f67a56.png)
![article_baseline_theme copy 8 2x](https://cloud.githubusercontent.com/assets/7339798/24308972/473ad2f8-1087-11e7-88b7-bd9e690e90b2.png)
![article_baseline_theme copy 9](https://cloud.githubusercontent.com/assets/7339798/24308975/473ed042-1087-11e7-9583-b85155f758da.png)
![article_baseline_theme copy 9 2x](https://cloud.githubusercontent.com/assets/7339798/24308974/473cf3bc-1087-11e7-92e6-3ee50124214a.png)
![article_baseline_theme copy 10](https://cloud.githubusercontent.com/assets/7339798/24308976/474ef6d4-1087-11e7-8ef0-a65a02a13024.png)
![article_baseline_theme copy 10 2x](https://cloud.githubusercontent.com/assets/7339798/24308977/47515064-1087-11e7-80b3-0ed724af1b1d.png)
![article_baseline_theme copy 11](https://cloud.githubusercontent.com/assets/7339798/24308979/47575a40-1087-11e7-9a15-2bb281ed5efb.png)
![article_baseline_theme copy 11 2x](https://cloud.githubusercontent.com/assets/7339798/24308978/4753c6aa-1087-11e7-89a7-5391b451f7c9.png)


1x and 2x versions. These probably need to be renamed. 
ready for dev, @ericlindley-g to either close or move to the next sprint for dev. im open to either.

**Comment by ericlindley-g** [comment]
Bumped into fixit sprint — assuming the images are sized the same as the old ones, is this replacement something you could do, @spacedino ?

**Comment by spacedino** [comment]
![theme3_coming_soon_2x](https://cloud.githubusercontent.com/assets/7339798/24532292/3e720e92-1574-11e7-9987-17ee323e6893.png)
![theme3_coming_soon](https://cloud.githubusercontent.com/assets/7339798/24532293/3e74b46c-1574-11e7-8632-798971e3b3f6.png)

i forgot about these two.

**Comment by spacedino** [comment]
PRs: 
- swap out images so the new ones have lorem ipsum #365
- replace 2x coming soon image #364
