### ISSUE TITLE
Landing page: new illustrations for template preview phone/tablet frames

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#278]

**Comment by spacedino** [comment]
![mobile](https://cloud.githubusercontent.com/assets/7339798/24019064/be0b1a3a-0a53-11e7-9302-5b5ef88c0b8d.png)

![mobile 2x](https://cloud.githubusercontent.com/assets/7339798/24019063/be0a6bbc-0a53-11e7-87de-d8e612281111.png)

**Comment by spacedino** [comment]
[tablet.svg.zip](https://github.com/ampproject/ampstart/files/894747/tablet.svg.zip)

**Comment by spacedino** [comment]
here's the new mobile image.
[mobile.svg.zip](https://github.com/ampproject/ampstart/files/894887/mobile.svg.zip)
