### ISSUE TITLE
Landing page: refine responsive behavior for template previews

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#279]
Currently it jumps around a bit. Was great for launch, but could bear refinement going forward

**Comment by spacedino** [comment]
@ericlindley-g  and i talked about a possible solution of adding more breakpoints to make it feel less glitchy, will need to circle back with @camelburrito . tabling it for now. 

i couldn't think of a great way to do this given the existing constraints. we might want to reconsider resizing below a certain breakpoint in the preview window until the transition completes. i know we did this to combat the iframe scroll bar originally but maybe its not worth it...the transition from the viewer to the "desktop" is the most glitchy for me...

**Comment by ericlindley-g** [comment]
Sounds good — thanks for exploring!  I'm tempted to just close this for now, in that case, since I can't see us getting around to changing this before doing the other pressing work.  WDYT?

**Comment by spacedino** [comment]
yep sg!
