### ISSUE TITLE
Use updated footer for site (and across ABE/ampproject.org)

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#288]
Needs updated text ( @spacedino to pass designs to @camelburrito when that's available)
Might also be good to include this footer in components, as a footer that accommodates more links

**Comment by spacedino** [comment]
design has been approved, waiting on content from Marketing.

https://folio.googleplex.com/amp-suite-branding/v3

![image](https://cloud.githubusercontent.com/assets/7339798/23954316/33d90d2c-0954-11e7-98aa-0181e11a5ff7.png)

**Comment by spacedino** [comment]
This is placeholder based on what we have now. "The AMP Project is an open-source initiative aiming to make the web better for all. The project enables the creation of websites and ads that are consistently fast, beautiful and high-performing across devices and distribution platforms."

need to follow up with Matt on Monday @spacedino

**Comment by spacedino** [comment]
got content from Matt, here is the final design. we can update both AMP Start and Amp By Example @sebastianbenz 

![image](https://cloud.githubusercontent.com/assets/7339798/24530334/21a80dd8-1566-11e7-8ce4-46f36766a18c.png)

passing back to @ericlindley-g for prioritization

**Comment by spacedino** [comment]
@camelburrito this one might be good for @torch2424
