### ISSUE TITLE
Baseline: Sidebar: "About" and "Contact" should have letter spacing of .01 rem

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#290]
"About" and "Contact" in sidebar should have letter spacing of .01 rem

**Comment by spacedino** [comment]
also its important to note that this needs to be updated in the templates as well

**Comment by camelburrito** [comment]
could we also start labeling these as` Baseline: Sidebar` in the title.

**Comment by ericlindley-g** [comment]
Good idea—done for this one. feel free to edit others as they come up, and we'll try to remember to do the same

**Comment by spacedino** [comment]
ive been using {page item is displayed on} - {description of bug} as my issue title format. Maybe we should have a consistent one...and I've been using  "Components / Templates" for items that affect both and "Baseline blog template" for things that only affect the template if that helps. If we use only "Baseline" it can be a little confusing if we just mean the components page or the baseline blog or article as well...

**Comment by spacedino** [comment]
@camelburrito i think this is fixed but will you confirm? we might have changed the letter spacing so i just want to document that.

**Comment by camelburrito** [comment]
I think we did a collab fix on this couple months ago, feel free to open if this does not look right
