### ISSUE TITLE
Baseline Blog Template - FOOD Category tag is missing

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#317]
Not sure what happened here...it was def on staging but its gone. Should match the mock ups.

**Comment by timBrockman** [comment]
#338 #341 Addressed the `#content` selector in the base-page.css file that was causing the issue. It probably just needs a rebuild.

**Comment by spacedino** [comment]
i will upload the original files eventually but I realized that because we made a lot of changes on staging, the mockups need to be retrofitted to the text and style changes we made live. we have another issue #339  to release the final files once everything is cleaned up. thanks for your patience!

**Comment by timBrockman** [comment]
Awesome! Mockups are just nice to have as a reference, but don't rush on my account.

**Comment by camelburrito** [comment]
This is fixed now
