### ISSUE TITLE
Components / Baseline article template - text below carousel is getting cut off

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#330]
![image](https://cloud.githubusercontent.com/assets/7339798/23925442/770a0d04-08cc-11e7-8cb4-cd894f666ca6.png)

**Comment by ericlindley-g** [comment]
My guess is that the sizing changed with the new image. For now I assume that we just have to manually update the sizing to accommodate the text + image, but it would be great to find some way for this to be less error prone in the future. Maybe through the configurator, maybe by bundling an actual component that combines the text with carousel...

/to @camelburrito for now to fix

**Comment by camelburrito** [comment]
AMP is all about authors being explicit with sizing ! We will need to make the accordion tall enough to accommodate the image and the text (may be we can try changing its layout to fill- then it might not be responsive  - we need to try it out.)
