### ISSUE TITLE
Drop cap isn't dropping

### ISSUE THREAD

**Issue by derekcecillewis** [ampproject/ampstart#331]
I'm pretty sure the drop cap  is not as it should be. See below, I believe the second image is how it should be.

![current-ampstart-dropcap](https://cloud.githubusercontent.com/assets/17770407/23926658/bbba703c-08eb-11e7-8d42-eff313e100b5.png)
![corrected-ampstart-dropcap](https://cloud.githubusercontent.com/assets/17770407/23926657/bbb924de-08eb-11e7-9af3-f03aade0d3c3.png)

**Comment by ericlindley-g** [comment]
+1   @camelburrito , is it possible to get this working in the classic dropcap sense?

/cc @spacedino

**Comment by camelburrito** [comment]
@ericlindley-g - very easy to make the change (one of the opinionated templates already has this.)

What exists is per design - the question should be if we need to change the design

**Comment by ericlindley-g** [comment]
Thanks! Passing to @spacedino then for thoughts

**Comment by spacedino** [comment]
so yea technically what we have is called an "Initial Cap" . We could rename it and then make another component "Drop Cap" that has the suggested behavior. @ericlindley-g @camelburrito what do you think?

thanks @derekcecillewis !

![image](https://cloud.githubusercontent.com/assets/7339798/23953303/72a6d8f2-0951-11e7-9af4-06673667e606.png)

some articles for reference:
http://theworldsgreatestbook.com/book-design-part-6/
http://www.magazinedesigning.com/drop-caps-and-initial-letters/

**Comment by ericlindley-g** [comment]
Thanks @spacedino!  Clarifying the language here in the way you describe would be nice. If it's quick to just re-name this feature for now to "initial cap", that seems worth doing, so we don't get in a backward-compatibility bind later if we want to introduce a true drop cap.  Is the re-name from "drop cap" to "initial cap" low effort to do, @camelburrito ?
