### ISSUE TITLE
Additional components audit + punchlist

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#332]
Need to break this down more, but there's room for a lot more components in AMP Start, particularly as new functionality is added to AMP (such as amp-bind).

This is first an issue to do an audit to determine promising candidates for components, then will be a prioritized punchlist to work through, first in design, then implementation

- [ ] Tooltip
....

/cc @camelburrito @spacedino @sebastianbenz for suggestions

**Comment by camelburrito** [comment]
We should plan this better syncing with other projects in the roadmap, closing this here.
