### ISSUE TITLE
Components / Article Template - fix tablet view "Recommended Articles" section

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#343]
![image](https://cloud.githubusercontent.com/assets/7339798/23971835/cb0c95fa-098c-11e7-90ab-23b25b9c4496.png)

**Comment by ericlindley-g** [comment]
@spacedino , is it easy to capture the differences in this bug, or something to work directly w/ @camelburrito  on?

**Comment by Lillian-wang** [comment]
@camelburrito , Would you please clarify the problem in the "Recommended Articles" section? Thanks.

**Comment by camelburrito** [comment]
<img width="1317" alt="screen shot 2017-06-19 at 2 18 28 pm" src="https://user-images.githubusercontent.com/1037311/27306375-3f82a330-54fa-11e7-8718-7a63b0e7a1a2.png">

**Comment by camelburrito** [comment]
@spacedino this is how it looks on tablets - is there something that you would like to have fixed here?
