### ISSUE TITLE
Test all components on opinionated templates

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#347]

**Comment by spacedino** [comment]
ok so i found some issues. 

![image](https://cloud.githubusercontent.com/assets/7339798/24023440/949a696a-0a69-11e7-9bfb-6ead0f2d3cae.png)

![image](https://cloud.githubusercontent.com/assets/7339798/24023445/9e83ebe0-0a69-11e7-84b4-aeff65a0edd8.png)

@camelburrito knows what to do. cc/ @ericlindley-g

**Comment by spacedino** [comment]
I still need to look at this with images and Theme 1. more TK..

**Comment by spacedino** [comment]
I'm going to change the title of this because I still need to do this for Theme 1.

**Comment by spacedino** [comment]
relted PR: UI components test page #359a
