### ISSUE TITLE
Designs (then implementation) for opinionated templates

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#35]
/to @abeck000  (Lucas working on designs)

**Comment by camelburrito** [comment]
@abeck000 - is this done ? can we publish the designs (Images here) and then close this.

**Comment by camelburrito** [comment]
We have tony's template ready and checked in , lets try and display it on the home page? (add the rest as coming soon?)

**Comment by ericlindley-g** [comment]
Sounds good — @spacedino, do you have images to use for previews of the opinionated templates?  What we can do is link the ones that get done in time, so they preview like the baseline templates, and just put "Coming soon" over the images of the ones that don't make it in time. Feel free to pick a representative page to use for each.

**Comment by spacedino** [comment]
this is done.
