### ISSUE TITLE
Theme 2 - check boxes broken

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#354]
needs check mark

![image](https://cloud.githubusercontent.com/assets/7339798/24062099/6690e1b2-0b17-11e7-8768-3b058592ba57.png)

**Comment by spacedino** [comment]
[icons_check_menu_close.zip](https://github.com/ampproject/ampstart/files/851822/icons_check_menu_close.zip)

@ericlindley-g  to prioritize cc @camelburrito to fix

**Comment by camelburrito** [comment]
# First Timers Only
We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes. (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

This particular starter issue is designed to familiarize you with the AMP Start Code Contribution.

# Background
[www.ampstart.com](www.ampstart.com) is a website that helps web developers to be able to download templates that are valid AMPs and use them on their pages. 


# What to do
- [ ] Create a test page (you can use the [template page](https://github.com/ampproject/ampstart/blob/master/templates/themes/2/home.amp.html) and add a check box in it to test it out  
OR 
[test.amp.html](https://github.com/ampproject/ampstart/blob/master/templates/test-all.amp.html) and point the css to theme2's css in the [JSON Config](https://github.com/ampproject/ampstart/blob/master/templates/themes/2/home.amp.json#L14))

- [ ] Now that you have replicated the problem try and figure out why the tick mark is not rendered in the checkbox.

- [ ] Most likely reason is `--color-input-secondary` css variable is not set in the [page-vars.css](https://github.com/ampproject/ampstart/blob/master/css/templates/themes/2/page-vars.css#L53) for theme 2. Check out the variables that need to be overridden to solve this in `page-vars.css` in this[ component css var file](https://github.com/ampproject/ampstart/blob/master/components/inputs/input-vars.css#L21).

### Step by step
- [ ] Claim this issue by adding a comment below.  Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you aren't too familiar with Git/GitHub, see the [Getting Started End-to-End Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md) for [an intro to Git & GitHub,](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#intro-to-git-and-github) and [how to get a copy of the code](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#get-a-copy-of-the-amphtml-code).  You can also refer to the [Quick Start Guide](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-quick.md) for the necessary setup steps with less explanation than the End-to-End guide.
- [ ] Follow the instructions for [building AMP Start ](https://github.com/ampproject/ampstart/blob/master/README.md).
- [ ] [Create a Git branch](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#create-a-git-branch) for making your changes.
- [ ] [Commit your changes](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#edit-files-and-commit-them) frequently.
- [ ] [Push your changes to GitHub](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#push-your-changes-to-your-github-fork).
- [ ] [Create a Pull Request](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#send-a-pull-request-ie-request-a-code-review).  Mention `closes Issue #442` in the description.
- [ ] Assign @camelburrito as the reviewer
- [ ] [Respond to your reviewer's comments](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#respond-to-pull-request-comments) (if any).

Once approved, your changes will be merged.  **⚡⚡⚡Congrats on making your first contribution to the AMP Project!⚡⚡⚡**  You'll be able to see it [live across the web soon]

hanks, and we hope to see more contributions from you soon.

### Questions?

If you have questions ask in this issue or on your Pull Request (mentioning @aghassemi) or see the [How to get help](https://github.com/ampproject/amphtml/blob/master/contributing/getting-started-e2e.md#how-to-get-help) section of the Getting Started guide.

**Comment by Lillian-wang** [comment]
I will be sending a change request shortly.
