### ISSUE TITLE
Theme 2 - drop cap missing indentation

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#355]
everything else works, just not that part...

Expected behavior: drop caps test should be left aligned with the indented body copy below it. All of the content should go past the main container. 

![image](https://cloud.githubusercontent.com/assets/7339798/24062162/a7f20122-0b17-11e7-9c11-3c46457ec282.png)

**Comment by camelburrito** [comment]
Looks like this has been fixed @spacedino can you please check again
