### ISSUE TITLE
Test all components on opinionated templates (Theme 1)

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#358]
this is the follow up to #347

**Comment by spacedino** [comment]
related PR: UI components test page #359

**Comment by spacedino** [comment]
bug checklist:

[ ] block quotes too small

![image](https://cloud.githubusercontent.com/assets/7339798/24221022/e4606ca2-0f09-11e7-9b8c-799a31fdebc4.png)

[ ] needs to be constrained at desktop version just ike the page.

**Comment by spacedino** [comment]
ready for dev / discussion.

**Comment by camelburrito** [comment]
I think this is done.
