### ISSUE TITLE
A11Y: User is able to navigate through background content without closing the Sidebar Menu

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#375]
**ENVIRONMENT:**

OS (number): N (7.1.2)
Build number: N2G47H
Form factor (Smartphone / tablet):  Nexus 6P
Browser: Chrome Dev 59.0.3056.4

**Pre-requisite:**
1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)))
2. Try to Linearly navigate through the Sidebar Menu.

**ACTUAL RESULTS:**

While Linearly navigating through the Sidebar Menu, user is able to navigate through the background content.

Note: Issue is also reproducible in iOS device.

**EXPECTED RESULTS:**

Focus should not go outside the Menu until it’s closed. i.e. user should not be able to to access the background content when Menu is opened.

**ATTACHMENT**

[BackgroundNavigation_MenuOpen.mp4.zip](https://github.com/ampproject/ampstart/files/906450/BackgroundNavigation_MenuOpen.mp4.zip)

**Comment by camelburrito** [comment]
https://github.com/ampproject/amphtml/issues/9847
