### ISSUE TITLE
[A11Y] Android: Focus issue causing inappropriate navigation through templates carousel present under "Build with AMP Start" heading

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#378]
**ENVIRONMENT:**

OS (number): N (7.1.2)
Build number: N2G47H
Form factor (Smartphone / tablet):  Nexus 6P
Browser: Chrome Dev 59.0.3056.4

**Pre-requisite:**
1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly navigate to the “Build with AMP Start” section.
3. Linearly navigate through the template carousel and move focus on the “previous item in carousel” button and double tap on it.

**ACTUAL RESULTS:**

Carousel is moved back a little to an extent where first and and second templates are displayed 50%. Focus remains on the “previous item in carousel” button and no annoucement/spoken feedback from talkback to notify user about the current state. 
If user tries to linearly navigates further,  focus goes to “next item in carousel” button.

**EXPECTED RESULTS:**

Carousel items should be moved appropriately i.e. after pressing “previous item in carousel” or “next item in carousel” button, only one appropriate carousel item should be in front with focus on it, so user can linearly navigate through the carousel items.

**ATTACHMENT**

Please refer to the attached screen recording.

[Template Carousel Navigation.mp4.zip](https://github.com/ampproject/ampstart/files/906425/Template.Carousel.Navigation.mp4.zip)

**Comment by ericlindley-g** [comment]
@camelburrito , I'm assuming this is a bug with amp-carousel?

**Comment by gkhadke** [comment]
@ericlindley-g  Similar issue is observed for the carousel present under the WANT section present on Blog post template page.

**Comment by torch2424** [comment]
@camelburrito I trust this is an `<amp-carousel>` issue, I can open an issue on the amphtml project so we can close this out. Is that okay?

**Comment by torch2424** [comment]
Confirmed that this is an issue with amp-carousel with @camelburrito , and accessiblity issues can be viewed on the main amphtml project: https://github.com/ampproject/amphtml/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20a11y%20carousel

Closing...
