### ISSUE TITLE
[A11Y] [iOS] User is able to linear navigate through the background content even when the Side Bar Menu is open.

### ISSUE THREAD

**Issue by spotukuchi** [ampproject/ampstart#384]
**ENVIRONMENT:**
Form factor : iPAD
Model : MC705LL/A
Version : 9.3.5(13G36)
Browser : Safari

**PRE-REQUISITE:**
Turn 'VoiceOver' ON. ( Settings->General->Accessibility->VoiceOver->ON )

**STEPS TO REPRODUCE:**
1. Open https://ampstart.com
2. Try to Linearly navigate through the items in Sidebar Menu.

**ACTUAL RESULTS:**
While Linearly navigating through the Sidebar Menu, user is able to navigate through the background content also.

**EXPECTED RESULTS:**
Focus should not go outside the Menu until it is closed. i.e. user should not be able to access the background content when Menu is open.

**Comment by ericlindley-g** [comment]
Looks like this bug might need to be fixed in AMP core — WDYT, @camelburrito ?

**Comment by camelburrito** [comment]
Yes this is an amphtml bug
