### ISSUE TITLE
[A11Y] Android: Focus goes to top of browser window instead of webpage when user navigates from one page to another

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#385]
**ENVIRONMENT:**

OS (number): N (7.0)
Build number: NRD91R
Form factor (Tablet):  Nexus 9
Browser: Chrome Dev 59.0.3062.4

**Pre-requisite:**
1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to COMPONENTS link and double tap on it.
3. When Components page is loaded, try to swipe linearly forward.

**ACTUAL RESULTS:**

Focus goes to the top of browser window and linear navigation happens through Tab name, URL, toolbar etc.

**EXPECTED RESULTS:**

Focus should go to the top of page opened and linear navigation should happen as per the page reading order from top.

**ATTACHMENT(S):**

[PageToPageNav_FocusIssue.mp4.zip](https://github.com/ampproject/ampstart/files/911781/PageToPageNav_FocusIssue.mp4.zip)

**Comment by camelburrito** [comment]
Dont think this can be fixed , this seems to be a browser thing.
