### ISSUE TITLE
[A11Y] Android: Carousel captions on components page are not displayed appropriately with regular/Large text and display size

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#392]
**ENVIRONMENT:**

OS (number): O
Build number: marlin-userdebug O MASTER eng.cbrowe.20170410.155415 dev-keys
Form factor (Smartphone / tablet):  PIXEL XL
Browser: Chrome Dev 59.0.3062.4

**PRE-REQUISITE**
Font size and display size are set to “Largest” (Settings > Accessibility)

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Tap on COMPONENTS link.
3. Verify the Carousel with captions section.

**ACTUAL RESULTS:**
Caption below respective carousel images is cutting off completely when font size and display size are set to “Largest”. Even with default font size and display size, some part of caption is cutting off.

Observation: Issue is only existing on smartphones. Verified on 6P and Pixel XL.

**EXPECTED RESULTS:**

Carousel image captions should be displayed appropriately for all size of font and display settings. Ensure that, actual scalable text is used for the captions. Images should not be used instead of text for the captions.

**ATTACHMENT(S):**

<img width="1440" alt="carouselwithcaptions_1" src="https://cloud.githubusercontent.com/assets/26986019/24933366/d2f89770-1eca-11e7-8861-f5a93d2aa4f1.png">
<img width="1440" alt="carouselwithcaptions_2" src="https://cloud.githubusercontent.com/assets/26986019/24933364/d2f78f10-1eca-11e7-9bfa-7946d4c0ff2b.png">
<img width="1440" alt="carouselwithcaptions_regularsize" src="https://cloud.githubusercontent.com/assets/26986019/24933365/d2f833fc-1eca-11e7-837d-4d55ed376b69.png">

**Comment by camelburrito** [comment]
This is a downside of amp-carousel itself not of amp start  - i did increase the height of the carousel as a part of this PR - https://github.com/ampproject/ampstart/pull/457
