### ISSUE TITLE
[A11Y] [iOS] Focus issues causing inappropriate navigation through templates carousel present under "Build with AMP Start" Heading.

### ISSUE THREAD

**Issue by spotukuchi** [ampproject/ampstart#394]
ENVIRONMENT:
Form factor : iPAD
Model : MC705LL/A
Version : 9.3.5(13G36)
Browser : Safari

Pre-requisite:
Turn 'VoiceOver' ON. ( Settings->General->Accessibility->VoiceOver->ON )

STEPS TO REPRODUCE:
1. Navigate to the URL:  https://ampstart.com
2. Linearly navigate to the “Build with AMP Start” section.
3. Linearly navigate through the template carousel and move focus on the “previous item in carousel” and "Next item in carousel" buttons and double tap on it.
4. Try to navigate further.

ACTUAL RESULTS:
Focus is stuck on those buttons when double tapped and does not navigate further.

EXPECTED RESULTS:
User should be able to double tap on either of the buttons and be able to perform respective actions and navigate further.

ATTACHMENT
Please refer to the Video in the below link for reference:

https://drive.google.com/corp/drive/folders/0BwgKOOZP99EuUzVWT25TVzl2S00

**Comment by camelburrito** [comment]
This is an amphtml issue , will open a amphtml bug for this.
