### ISSUE TITLE
[A11Y] [iOS] Social Media Share buttons do not have appropriate labels assigned.

### ISSUE THREAD

**Issue by spotukuchi** [ampproject/ampstart#395]
ENVIRONMENT:
Form factor : iPAD
Model : MC705LL/A
Version : 9.3.5(13G36)
Browser : Safari

Pre-requisite:
Turn 'VoiceOver' ON. ( Settings->General->Accessibility->VoiceOver->ON )

STEPS TO REPRODUCE:

1. Open https://ampstart.com
2. Linearly navigate to the “Article” template and double tap on View Template
3. Linearly navigate to READ MORE section and try to move focus on social media buttons using linear navigation or exploratory touch and observe what Voiceover reads for each icon label.

ACTUAL RESULTS:
Social media share buttons are labelled as "Link".

EXPECTED RESULTS:
The social media share buttons should have appropriate labels and controls assigned to it.

ATTACHMENT(S):
Please refer to the videos in the below link for reference:

https://drive.google.com/corp/drive/folders/0BwgKOOZP99EuUzVWT25TVzl2S00

**Comment by torch2424** [comment]
I trust that the PR reference will close this issue.
