### ISSUE TITLE
[A11Y] Android: Redundant/Multiple focus on same component causing label and placeholder text to be read inappropriately

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#396]
**ENVIRONMENT:**

OS (number): O
Build number: marlin-userdebug O MASTER eng.cbrowe.20170410.155415 dev-keys
Form factor (Smartphone / tablet): PIXEL XL
Browser: Chrome Dev 59.0.3062.4

**PRE-REQUISITE**

1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to COMPONENTS link and double tap on it.
3. Linearly navigate through different components present on the page.

**ACTUAL RESULTS:**

Components are labeled inappropriately in the following way:

1. Text Box:
Placeholder text is used as a able. So talkback reads the placeholder text twice. First time as a label and second time as a hint text. So talkback reads it as “Enter your Name Enter your Name This input is disabled, Edit box”. On further linear navigation, Placeholder text/hint text is focused again. So talkback again reads it as “Enter your name”

2. Date Picker:
When focused moved on date picker, talk says, “Date of expiry, date picker”. If user navigates further, talkback says, “Date of expiry”

Note: Similar pattern of issues mentioned above is followed by other components.

**EXPECTED RESULTS:**

Label and Placeholder text should be read appropriately without causing any redundancy or repetition.

**ATTACHMENT(S):**

[Components_LinearNavigation.mp4.zip](https://github.com/ampproject/ampstart/files/915031/Components_LinearNavigation.mp4.zip)

**Comment by torch2424** [comment]
Please see #415 for the date input accessibility discussion

**Comment by camelburrito** [comment]
This is not related to #415?

**Comment by torch2424** [comment]
Oh my apologies, you are correct, I misread the description, thanks for catching that!
