### ISSUE TITLE
[A11Y] Android: Date picker doesn’t open appropriately with talkback

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#397]
**ENVIRONMENT:**

OS (number): O
Build number: marlin-userdebug O MASTER eng.cbrowe.20170410.155415 dev-keys
Form factor (Smartphone / tablet): PIXEL XL
Browser: Chrome Dev 59.0.3062.4

**PRE-REQUISITE**

1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to COMPONENTS link and double tap on it.
3. Linearly navigate to date picker and try to open it.

**ACTUAL RESULTS:**

On moving focus on date picker, talkback says “Date of Expiry, date picker” “double tap to change”. Upon double tapping nothing happens. If user navigates linearly further, talkback just says “Date of expiry”. But, here the actual double tap works properly and opens up the date picker.

**EXPECTED RESULTS:**

Control type and focus should be assigned appropriately for the date picker

**ATTACHMENT(S):**

[Date Picker.mp4.zip](https://github.com/ampproject/ampstart/files/915071/Date.Picker.mp4.zip)

**Comment by torch2424** [comment]
Please see #415 for the date input accessibility discussion

**Comment by camelburrito** [comment]
@torch2424 - this i think we might need to fix, please check

**Comment by camelburrito** [comment]
I guess the fix for this is to make the label aria-hidden

**Comment by torch2424** [comment]
Oh yes you are correct, fixing now
