### ISSUE TITLE
[A11Y] Android: No announcement of percentage after adjusting the slider using volume key

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#398]
**ENVIRONMENT:**

OS (number): O
Build number: marlin-userdebug O MASTER eng.cbrowe.20170410.155415 dev-keys
Form factor (Smartphone / tablet): PIXEL XL
Browser: Chrome Dev 59.0.3062.4

**PRE-REQUISITE**

1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to COMPONENTS link and double tap on it.
3. Linearly navigate to “Select a range” slider and adjust the slider using volume keys.

**ACTUAL RESULTS:**

Slider is adjusted but there is no announcement of slider adjustment percentage by talkback.

**EXPECTED RESULTS:**

Slider adjustment percentage should be announced after moving the slider using volume keys.

Also, slider Percentage should be displayed visually as well. For sighted users, it is not possible to determine the degree of adjustment. So showing percentage will give that info.

**ATTACHMENT(S):**

[Slider Adjustment.mp4.zip](https://github.com/ampproject/ampstart/files/915084/Slider.Adjustment.mp4.zip)

**Comment by torch2424** [comment]
Would like #492 to be pulled before doing this to avoid large merge conflicts.

Also, I plan to use this MDN doc to acheive as much as I can: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role

**Comment by torch2424** [comment]
The MDN I linked did not work for talkback in announcing the current value, and after reading this: https://ux.stackexchange.com/questions/80876/how-do-you-make-a-range-input-slider-accessible-to-screen-readers-for-blind-ux

I assume we may need to programmatically update a value that is then read by a screen reader. Unfortunately, this would require a new amp-extension, as we cannot add our own JS. Does that sound correct @camelburrito

**Comment by camelburrito** [comment]
Yeah , this is a browser issue and AMP does not make it any worse/better.
