### ISSUE TITLE
[A11Y] Android: Unwanted element is focused for pop-up button components

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#399]
**ENVIRONMENT:**

OS (number): O
Build number: marlin-userdebug O MASTER eng.cbrowe.20170410.155415 dev-keys
Form factor (Smartphone / tablet): PIXEL XL
Browser: Chrome Dev 59.0.3062.4

**PRE-REQUISITE**

1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to COMPONENTS link and double tap on it.
3. Try to Linearly navigate through different types of “pop-up” buttons on the page.

**ACTUAL RESULTS:**
While navigating through different pop up buttons. User is able to move focus on unwanted unlabeled element “V” (more like a down arrow for dropdown list).

**EXPECTED RESULTS:**

User should not be able to move focus on unwanted elements.

**ATTACHMENT(S):**

[UnwantedElement_Pop-up_Button.mp4.zip](https://github.com/ampproject/ampstart/files/915118/UnwantedElement_Pop-up_Button.mp4.zip)

**Comment by torch2424** [comment]
the "v" is in a css after, and we could not find a way to hide an element from screen readers using only css that is supported by all browsers. The label has been fixed in previous PRs, for instance #490
