### ISSUE TITLE
UX review & fixes for site

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#40]
When the time is right, @abeck000 should do a review for UX polish on the site, and file bugs (along with associated severity: P1 (launch blocking), P2 ("should" do), P3 (nice to have), so @camelburrito can make fixes before launch.

**Comment by abeck000** [comment]
i think we're ready for this @ericlindley-g

**Comment by abeck000** [comment]
oops this comment was meant for another issue.

**Comment by camelburrito** [comment]
This can be closed now we have other bugs
