### ISSUE TITLE
[A11Y] Android: "Carousel with text" have heading level 1 assigned to the text associated with the images

### ISSUE THREAD

**Issue by gkhadke** [ampproject/ampstart#400]
**ENVIRONMENT:**

OS (number): O
Build number: marlin-userdebug O MASTER eng.cbrowe.20170410.155415 dev-keys
Form factor (Smartphone / tablet): PIXEL XL
Browser: Chrome Dev 59.0.3062.4

**PRE-REQUISITE**

1. Talkback is ON

**STEPS TO REPRODUCE:**

1. Open [https://ampstart.com](https://ampstart.com)
2. Linearly Navigate to COMPONENTS link and double tap on it.
3. Try to Linearly navigate through “Carousel with text” present on the page.

**ACTUAL RESULTS:**

When focus is moved on the image inside the carousel, talkback reads the filename of the image. On further linear navigation focus goes on to the text associated with the image and talkback reads it along with a heading level 1.

Note: It's Ok to have a Image with text having heading level 1, if it's a separate image. But for an Image inside carousel, it doesn't look appropriate as it's breaking the hierarchy here.

**EXPECTED RESULTS:**

Associated text should not have heading level 1 assigned to it. Also, heading levels should be used only if required and it must follow appropriate hierarchy levels w.r.t Main section and Subsections of the page.

**ATTACHMENT**

<img width="1440" alt="carouselwithtext" src="https://cloud.githubusercontent.com/assets/26986019/24971178/d1aff36c-1f6b-11e7-97ee-ef49747453d5.png">

**Comment by spotukuchi** [comment]
This issue is reproducible in the below environment:

**ENVIRONMENT:**
Form factor : iPAD
Model : MC705LL/A
Version : 9.3.5(13G36)
Browser : Safari

**PRE-REQUISITE:**
Turn 'VoiceOver' ON. ( Settings->General->Accessibility->VoiceOver->ON )

Steps to reproduce, Actual and Expected results are same as the original bug above.
