### ISSUE TITLE
[A11Y] [iOS] Improper focus causing navigation issues in the Side bar menu in "What is AMP?" page.

### ISSUE THREAD

**Issue by spotukuchi** [ampproject/ampstart#401]
**ENVIRONMENT:**
Form factor : iPAD
Model : MC705LL/A
Version : 9.3.5(13G36)
Browser : Safari

**PRE-REQUISITE:**
Turn 'VoiceOver' ON. ( Settings->General->Accessibility->VoiceOver->ON )

**STEPS TO REPRODUCE:**
1. Navigate to the URL: https://ampstart.com/
2. Navigate to "What is AMP?" link in the side bar menu and double tap on it.
3. Linear navigate to the Side Bar Menu in this page and double tap on it.
4. Try to linear navigate through the menu items and observe what VoiceOver reads and Where the focus is placed.

**ACTUAL RESULTS:**
While Linearly navigating through the Sidebar Menu, VoiceOver reads through the background page content, thus the user not being able to navigate through the menu items.

**EXPECTED RESULTS:**
User should be able to linear navigate through all the menu items. Focus should not go outside the Menu until it is closed. i.e. user should not be able to access the background content when Menu is open. 

**ATTACHMENT:**
Please see the video in the link below for reference.

https://drive.google.com/corp/drive/folders/0BwgKOOZP99EuUzVWT25TVzl2S00

**Comment by camelburrito** [comment]
This is an ampproject.org issue.
