### ISSUE TITLE
[A11Y] [iOS] Side bar Menu and Close button inside the menu are inappropriately labelled in "What is AMP?" page.

### ISSUE THREAD

**Issue by spotukuchi** [ampproject/ampstart#402]
**ENVIRONMENT:**
Form factor : iPAD
Model : MC705LL/A
Version : 9.3.5(13G36)
Browser : Safari

**PRE-REQUISITE:**
Turn 'VoiceOver' ON. ( Settings->General->Accessibility->VoiceOver->ON )

**STEPS TO REPRODUCE:**

1. Navigate to the URL: https://ampstart.com/
2. Navigate to "What is AMP?" link in the side bar menu and double tap on it.
3. Linear navigate to the Side Bar Menu in this page and observe what Voice Over announces and then double tap on it.
4. Navigate to the Close button and observe what Voice Over announces.

**ACTUAL RESULTS:**
Sidebar menu is labelled as "Button and banner" and close button is labelled as "Button".

**EXPECTED RESULTS:**
Sidebar Menu and Close buttons should have appropriate labels assigned.

**ATTACHMENT:**
Please see the video in the link below for reference.

https://drive.google.com/corp/drive/folders/0BwgKOOZP99EuUzVWT25TVzl2S00

**Comment by torch2424** [comment]
Fixed in my a11y bugs branch

[Commit Fix](https://github.com/torch2424/ampstart/commit/eeb8d43395d09cb39e26ac860625acbbcd310507)
