### ISSUE TITLE
[A11Y] [Web] Linked Icons at bottom of Template page not properly labeled

### ISSUE THREAD

**Issue by shengoogle** [ampproject/ampstart#411]
ENVIRONMENT:
Build number: 56.0.2924.87 beta (64-bit)
Form factor: Chromebook
Browser: Chrome

PRE-REQUISITE
chromevox is ON

STEPS TO REPRODUCE:
Open https://ampstart.com
Navigate to Templates tab
Using chromevox, navigate to share icon links located at bottom of page
Navigate through icons

ACTUAL RESULTS:
Using chromevox, user can navigate to linked icons at bottom of template main landing page.  As user navigates through icons, icons read off with twitter and wordpress but github and slack have no identification of what icon is.

EXPECTED RESULTS:
Icons are labeled correctly

ATTACHMENT:
Please see the video in the link below for reference.

https://drive.google.com/open?id=0BwUNSMCBrCB4WmM3cGU5WTJvWVE

**Comment by torch2424** [comment]
Fixed in my a11y bugs branch

[Commit Fix](https://github.com/torch2424/ampstart/commit/56af488b7297f1f8c972b08a4e73b4481009d214)
