### ISSUE TITLE
[A11Y] [Web] Focus is not set on Template Preview pop-up

### ISSUE THREAD

**Issue by shengoogle** [ampproject/ampstart#412]
ENVIRONMENT:
Build number: 56.0.2924.87 beta (64-bit)
Form factor: Chromebook
Browser: Chrome

PRE-REQUISITE
chromevox is ON

STEPS TO REPRODUCE:
Open https://ampstart.com
Navigate to Templates tab
Using chromevox, navigate to article
Navigate to view templates button and click

ACTUAL RESULTS:
Using chromevox, navigate view templates button and select.  Pop up will appear with template sample.  Focus is not oriented on the pop up template and is still set on the background page.

EXPECTED RESULTS:
User focus is set on pop up template.

ATTACHMENT:
Please see the video in the link below for reference.

https://drive.google.com/open?id=0BwUNSMCBrCB4VzNtTXFoemxzcjg

**Comment by torch2424** [comment]
Hello,

after investigating, this appears to show a lightbox using on="tap:{{lightbox-id}}". Unfortunately after reviewing AMP's [Actions and events](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md) it appears we can not set focus on an element id from the same event chain. Therefore, we may need to expose this in AMP itself.

**Comment by camelburrito** [comment]
Opened an amphtml issue for this.
