### ISSUE TITLE
[A11Y] [Web] Close button in preview template mode labeled incorrectly

### ISSUE THREAD

**Issue by shengoogle** [ampproject/ampstart#413]
ENVIRONMENT:
Build number: 56.0.2924.87 beta (64-bit)
Form factor: Chromebook
Browser: Chrome

PRE-REQUISITE
chromevox is ON

STEPS TO REPRODUCE:
1. Open https://ampstart.com
2. Using chromevox, to Templates tab
3. Navigate to view template button.
4. Open Template
5. Navigate to X button in pop up preview menu

ACTUAL RESULTS:
Using chromevox, navigate view templates button and select.  Pop up will appear with template sample.  Once user is navigating through template preview and selects the side list, close button for list reads out incorrectly

EXPECTED RESULTS:
X button reads out close or something similar.

ATTACHMENT:
Please see the video in the link below for reference.

https://drive.google.com/open?id=0BwUNSMCBrCB4Q3F1OVliaGh0dms

**Comment by torch2424** [comment]
Fixed in my branch

[Commit Fix](https://github.com/torch2424/ampstart/commit/ce0003bef4689dcedd22ad896826d418532b7a3f)
