### ISSUE TITLE
[A11Y] [Web] Amp Start Logo incorrectly reads "the blog"

### ISSUE THREAD

**Issue by shengoogle** [ampproject/ampstart#414]
ENVIRONMENT:
Build number: 56.0.2924.87 beta (64-bit)
Form factor: Chromebook
Browser: Chrome

PRE-REQUISITE
chromevox is ON

STEPS TO REPRODUCE:
1. Open https://ampstart.com
2. Navigate to Templates tab
3. Using chromevox, navigate amp start logo at left top of screen

ACTUAL RESULTS:
Using chromevox, navigate view templates and navigate to Amp Start Logo. Logo reads “the blog”

EXPECTED RESULTS:
Logo reads Amp Start

ATTACHMENT:
Please see the video in the link below for reference.

https://drive.google.com/open?id=0BwUNSMCBrCB4MmJJZzA1czc4b2s

**Comment by torch2424** [comment]
Fixed in my a11y bugs branch.

[Commit Fix](https://github.com/torch2424/ampstart/commit/fa626ced64cc6b9ec023fb0fbe654c4fdb3d8db5)
