### ISSUE TITLE
[A11Y] [Web] Hidden Image under Navigation

### ISSUE THREAD

**Issue by shengoogle** [ampproject/ampstart#418]
ENVIRONMENT:
Build number: 56.0.2924.87 beta (64-bit)
Form factor: Chromebook
Browser: Chrome

PRE-REQUISITE
chromevox is ON

STEPS TO REPRODUCE:
1. Open https://ampstart.com
2. Navigate to Components Tab
3. Using chromevox, Navigate to Navigation header and move through Responsive Menubar options
4. Navigate to blank image left of “fashion” button 

ACTUAL RESULTS:
Hidden image reads “the blog”

EXPECTED RESULTS:
Image should be shown and properly labeled

ATTACHMENT:
https://drive.google.com/open?id=0BwUNSMCBrCB4WU14bjBacGFFUGM

**Comment by torch2424** [comment]
Fixed in my a11y bugs branch

[Commit Fix](https://github.com/torch2424/ampstart/commit/53d3fff71d52af0d00dbb1bf6348030ce3b35101)
