### ISSUE TITLE
remove side nav before 833 px wide

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#420]
switch to tablet view sooner to avoid -OR- don't shrink sidebar to avoid the text in the sidebar colliding with the edge of the side bar

![image](https://cloud.githubusercontent.com/assets/7339798/25057305/858f9bb8-2123-11e7-9adf-80279061651e.png)

**Comment by spacedino** [comment]
@ericlindley-g to prioritize

**Comment by Lillian-wang** [comment]
I have pushed up the changes in the following CL.
