### ISSUE TITLE
AMP-Social-Share icons are black and white

### ISSUE THREAD

**Issue by devilbags** [ampproject/ampstart#428]
All the icons are black and white

Wouldn't it be a good choice to make it colored as their site's theme. Like in amp-example

**Comment by ericlindley-g** [comment]
The theme was originally designed to override those default styles to get a particular look in the context of this template. (It's worth noting that developers can delete those styles to get the original colors back).  Though using the original colors might be worth considering — /cc @spacedino for thoughts

**Comment by spacedino** [comment]
@devilbags thanks for your feedback! if i am understanding correctly - you would like an attribute that will link a theme color to the share icons, like this example referenced on AMP By Example?

![image](https://cloud.githubusercontent.com/assets/7339798/25287967/56169e5e-2678-11e7-812f-31e1bfc66c60.png)

In our baseline theme we do this for the follow icons, not the share icons to explicitly show a distinction between a companies brand affiliate sites and icons that launch a share modal.

![image](https://cloud.githubusercontent.com/assets/7339798/25287996/6cff2cda-2678-11e7-99b1-f69acd3fc3e3.png)

we have a ticket to clean up the share icons, we could consider this, but i think a distinction between share and follow is necessary. was there a reason why you saw the black and white representation as a problem?

**Comment by camelburrito** [comment]
@ericlindley-g can we close this ?

**Comment by ericlindley-g** [comment]
@devilbags  — Closing this issue, but feel free to re-open if you have more thoughts based on @spacedino 's questions.
