### ISSUE TITLE
footer component should be responsive

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#440]
Use case:
1. on mobile / tablet text for too many sections that don't fit > text stacks at a certain break point
2. on mobile / tablet text in a single section does not fit > first text should stack > if that doesnt fix it > do we wrap the text? 

cc @ericlindley-g for triage and @camelburrito 

Example of what should NOT happen:
desktop vs. mobile
![screen shot 2017-05-18 at 1 53 13 pm](https://cloud.githubusercontent.com/assets/7339798/26223834/b8040180-3bd4-11e7-9dce-de0b6198a245.png)
![screen shot 2017-05-18 at 1 53 26 pm](https://cloud.githubusercontent.com/assets/7339798/26223837/b9c9d6f2-3bd4-11e7-8a72-a2462878850a.png)

**Comment by camelburrito** [comment]
@ericlindley-g you will need to add space in between your super long text and it will break at spaces

**Comment by camelburrito** [comment]
<img width="336" alt="screen shot 2017-06-12 at 1 31 34 pm" src="https://user-images.githubusercontent.com/1037311/27053804-840205f0-4f73-11e7-853f-69c12f089e1b.png">
