### ISSUE TITLE
Images broken when served from Google AMP Cache

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#445]
Test link: https://ampstart-com.cdn.ampproject.org/c/s/ampstart.com

Working when served through viewer, so not a P0

**Comment by ericlindley-g** [comment]
Strange—adding "/" at the end fixes this:  https://ampstart-com.cdn.ampproject.org/c/s/ampstart.com/ works

**Comment by camelburrito** [comment]
This should be viewer
@alf7 @ericfs

**Comment by alf7** [comment]
@vitaliybl 

It actually *does* work in the viewer. Just not when accessed directly through the AMP Cache. Looking at the SVG's URL in the page Eric linked, it seems like the www.ampstart.com is missing from the path.

**Comment by camelburrito** [comment]
to be clear

`https://ampstart-com.cdn.ampproject.org/c/s/ampstart.com` is broken 

while 

`https://ampstart-com.cdn.ampproject.org/c/s/ampstart.com/` works

**Comment by vitaliybl** [comment]
This is almost WAI from my perspective - the first URL should probably just 404. The slash after origin host is not optional.

**Comment by ericlindley-g** [comment]
Works for me — and I suppose it's documented that platforms should be using the URL API anyway, so this shouldn't be an issue in practice. Closing now, but feel free to re-open if there's any disagreement
