### ISSUE TITLE
Gulp watch hanging

### ISSUE THREAD

**Issue by gurmukhp** [ampproject/ampstart#472]
On first run, the gulp watch task runs without hanging. However once a file has changed, the watch task hangs on either Highlight or Img. Removing clean, bundle and highlight resolves this.

```
// Hangs
gulp.task('build', 'build', function(cb) {
  runSequence('clean', 'highlight', 'img', 'postcss', 'posthtml', 'www',
      'validate', 'bundle', cb);
});

// Works fine
gulp.task('build', 'build', function(cb) {
   runSequence('img', 'postcss', 'posthtml', 'validate', cb);
});
```

After 5 mins or so the task does finish.

Is it possible to make the watch task faster?

**Comment by camelburrito** [comment]
@gurmukhp - did you send a PR to resolve this?

**Comment by gurmukhp** [comment]
No, I was hoping it would be fixed on your side. Have been using a heavily modified gulpfile in the interim.

**Comment by camelburrito** [comment]
ok we will fix it then ! Thanks (was confused since you had sent multiple fixes :) )
