### ISSUE TITLE
Template partials 

### ISSUE THREAD

**Issue by WillDonohoe** [ampproject/ampstart#477]
It would be useful if we could split up markup within our templates into partials and importing them via mustache in the interest of keeping the main template html file unbloated during development.

While this is possible at the moment, the AMP validator will validate any html file inside the templates folder and fail when it finds a partial. A proposal to get around this would be to create a partials directory inside each theme folder, and make an exception in the gulp task to avoid validating these files.

**Comment by gurmukhp** [comment]
I've created a fix for this in my recent PR #479

**Comment by camelburrito** [comment]
@gurmukhp Can this be closed now ?

**Comment by gurmukhp** [comment]
Yes :)
