### ISSUE TITLE
Landing page bug punchlist

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#48]
P1 (high priority)

- [x] Fix device preview so it fits on a wide screen — TOP PRIORITY
- [x] Templates need "Download Code" buttons — TOP PRIORITY
- [x] update with copy when final
- [x] update footer with privacy and terms ( @ericlindley-g for links when ready, @spacedino for design updates)
- [x]  Replace template preview images with hi-res images of the templates (will need to make sure the image representation of the templates are the right size and match the size in the mobile preview display) / to @abeck000 to provide assets
- [x] use correct fonts (right now they are Helvetica)
- [x] "Flexible" has "pb2 caps mb3 h3 relative" class while "Responsive" and "Open Source" have "www-heading pb2 caps mb3 h3 relative"  ( @abeck000: which should it be? ... @ericlindley-g no idea. i defer to sriram. i just know they should match the mock ups and be the same.") this is actually just part of the above bug. ^
- [x] Add box-shadow to template images
- [x] rollover should be underline in nav bar, remove current interaction
- [x] "view mobile" and "view templates" should be right and left aligned accordingly (toward outer edge of screen)
- [x] grey boxes for each template should be full bleed
- [x] update wordpress link
- [x] "Built with AMP Start" should link to interactive previews of actual templates (pending implemented designs)
- [x] Address large spacing on page with wide screens (@cramforce's feedback). Restrict column of content to 850px & update design to spec (/to @spacedino  and @camelburrito  to work together to solve)
- [x] Use hi-res assets for site images (esp templates) (/to @spacedino to provide)
- [x] fix horizontal spacing of page - will need adjustments ( /to @abeck000 to provide specifics)
- [ ] X in side bar is too big and spacing looks off ( /to @abeck000 to provide specifics — may just want to use smaller image with large tap-target) -  MOVED TO ISSUE #264

- [x] buttons are too small, padding is off ( /to @abeck000 to provide specifics)
- [x] we may need to revisit the 831px tablet break point. The text for the principles section looks odd. ( /to @abeck000 to update design)
- [ ] the bottom of the page should scroll up over the gradient area, like a flying carpet

P2 (Medium-priority)
- [ ] fix spacing below H2s "Full Page Templates" and  "Built with AMP Start"> should be 80px (not 56px)
- [ ] external links should open in a new window
- [ ] Use motion previews for templates
- [ ] Clicking on template images should open preview modal

P3 (Low-priority)

- [ ] update footer when design is complete ( /to @abeck000 to provide specifics)
- [ ] hide scroll bar in carousel for "Built with AMP Start"
- [ ] weird blue outline on buttons on click (@abeck000: this is the default "focus" state for the browser. we can design a different version of this, but [some folks recommend not to](https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/)

Fixed

- [x] add missing line under "FLEXIBLE" 
- [x] "view template" on mobile is broken
- [x] "Templates" link is broken

**Comment by abeck000** [comment]
@ericlindley-g thats everything i found so far. does that priority look accurate? feel free to rearrange

**Comment by ericlindley-g** [comment]
Awesome—thanks @abeck000 ! I'll take a look and rearrange (will let you know if I add/rearrange anything)

**Comment by spacedino** [comment]
closing, separated remaining issues.
