### ISSUE TITLE
Not enough padding in main headline

### ISSUE THREAD

**Issue by cramforce** [ampproject/ampstart#496]
<img width="318" alt="screen shot 2017-07-07 at 12 31 08 pm" src="https://user-images.githubusercontent.com/89679/27973814-3a6030f6-6310-11e7-87c2-7d4626fcc0f1.png">

I think the typography can be fine tuned here. There is not enough space left of the `G` and right of the `h`.

**Comment by camelburrito** [comment]
![localhost-5000- iphone 6](https://user-images.githubusercontent.com/1037311/31518222-6b0535a0-af53-11e7-9c05-e42e7fd5a257.png)

Will be fixed after today's release
