### ISSUE TITLE
[navbar] Animating icon based on sidebar open/closed status

### ISSUE THREAD

**Issue by ciampo** [ampproject/ampstart#499]
I'm trying to animate the hamburger icon when the sidebar opens/closes (something like [this](https://codepen.io/designcouch/pen/Atyop)).

I noticed I can inject a custom SVG through the `svg-trigger` property, but I can't still find a way of animating it with CSS when the sidebar toggles.

`amp-bind` can't listen to toggle events from `amp-sidebar`. If the `amp-sidebar` component came before the `header` in terms of DOM order, I could use CSS to achieve my effect `amp-sidebar[open] ~ .ampstart-headerbar svg {...}`, but this is not the case.

Do you have any suggestion on how to achieve this effect with the navbar component?

**Comment by camelburrito** [comment]
I guess we could move the sidebar to be the first element and update navbar.css here - https://github.com/ampproject/ampstart/blob/master/components/navbar/navbar.css#L24
