### ISSUE TITLE
Default spacing in bass-override-vars isn't being considered

### ISSUE THREAD

**Issue by gurmukhp** [ampproject/ampstart#532]
bass-override-vars defines space-4 as 2rem which means pb4 should be:

`padding-bottom: 2rem;`.

However it is actually compiling out to:

`padding-bottom: 4rem`

If the spaces are redefined in the templates page-vars, this problem goes away.

**Comment by camelburrito** [comment]
i think i know why this is happening . 

in css/core.css - we import bass first and then our overrides, the bass modules should be included somewhere inbetween , I think there is a gulp plugin that does conditional imports i will look into it. 

meanwhile , you can reimport bass-override-vars.css after the module import, or try and import the module before core , let me  know how it works.

**Comment by gurmukhp** [comment]
Moving the modules to before the core.css did the trick. Thanks!
