### ISSUE TITLE
Components page - bug punchlist

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#54]
P1

- [x] Need indication of what amp-* extensions to include with each component ( @abeck000 to design)
- [ ] Need solution for iframe issue on page: currently on mobile it's easy to get stuck scrolling through scrolling iframes within scrolling viewport. /to @abeck000 to work w/ @camelburrito on a solution ( @ericlindley-g as needed) — maybe could put code snippets in accordions on mobile?
- [ ] Need way to get back to landing page ( @abeck000 to design — same goes for all non-landing pages)
- [ ] Ranged input doesn't appear in chrome mobile emulator:

<img width="455" alt="screen shot 2017-02-20 at 3 16 13 pm" src="https://cloud.githubusercontent.com/assets/16807766/23144895/9a98c23c-f77f-11e6-9d6f-00c61c860efd.png">
- [ ] Disabled inputs (range, text, etc) don't appear in iOS Chrome
- [ ] Opening sidebar abruptly scrolls user partway down the page in iOS Chrome
- [ ] Add dropshadow around nav bar iframes

P2

- [ ] Somehow fill in the area below sidebar/header examples so it's clear that there's not an empty space (@abeck000 to design)
- [ ] Add padding around text in code snippets (text shouldn't go all the way to left edge of the container (@abeck000 to give designs, but I imagine there's already a standard padding that can be applied)

P3

- [ ] Low-priority item 3

/to @abeck000 to fill out

**Comment by spacedino** [comment]
moved open issues to their own bugs, closing @ericlindley-g
