### ISSUE TITLE
Look into reducing repository size, from reducing number of unused references

### ISSUE THREAD

**Issue by torch2424** [ampproject/ampstart#552]
For instance, look at the discussion here: https://stackoverflow.com/questions/3797907/how-to-remove-unused-objects-from-a-git-repository

Two things to be wary of however:

* This may have unwanted effects, therefore, we may want to look into having another copy, or some sort of test.
* In my experience on smaller teams, something like this would happen during a code freeze. If this is the case, we may not want to do this at all.

**Comment by rsimha-amp** [comment]
@torch2424, this sounds like a good idea. Do we have an estimate for the potential size savings for `ampproject/amphtml`?

/cc @erwinmombay @cramforce

**Comment by torch2424** [comment]
Well, after a fresh `git clone`, we have a directory size of 315M, and by deleting the .git folder, we get down to 62M. And from what I can tell the download size is 251.45M.

After running `git gc --aggressive`, I got the repo size down to 174M

**Comment by rsimha-amp** [comment]
@erwinmombay @cramforce, do you think this is worth doing?

**Comment by rsimha-amp** [comment]
@erwinmombay @choumx, do we think we'll lose any useful history by `git gc`ing our repository?

**Comment by choumx** [comment]
I think GitHub performs `git gc` automatically: https://twitter.com/githubhelp/status/387926738161774592?lang=en

Really reducing the size would probably require losing some history, for example: https://gitlab.com/help/user/project/repository/reducing_the_repo_size_using_git.md

**Comment by erwinmombay** [comment]
from what ive been told we don't need to dc

**Comment by torch2424** [comment]
@choumx Oh, you are right. Well, thank you for doing the research, I'll close this. Thanks!
