### ISSUE TITLE
Fetch as Google - Test My Site - PageSpeed Insights - Preview Problem 

### ISSUE THREAD

**Issue by Polylike** [ampproject/ampstart#597]
Hello,

should i worried about when Google Search Console, Google Test My Site and PageSpeed Insights sees preview/see only the navigation of AMP Start Theme?

![pagespeed insights](https://user-images.githubusercontent.com/16958775/29537746-259c4f5c-86c3-11e7-90f7-4928b5f649ed.PNG)
![test my site](https://user-images.githubusercontent.com/16958775/29537747-259e5518-86c3-11e7-892d-c04c0d977177.PNG)

Thanks,
Daniel

**Comment by camelburrito** [comment]
I actually do not know the answer to this, but you could ask the search console help - https://support.google.com/webmasters/?hl=en#topic=3309469
