### ISSUE TITLE
[ampstart.com] preview pane - design

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#605]

**Comment by spacedino** [comment]
![12_preview_desktop copy](https://user-images.githubusercontent.com/7339798/31339634-6f91e5b4-acfb-11e7-9311-874b92e16884.png)

**Comment by spacedino** [comment]
amendment - move the icons to the top bar next to "download" in the center of the page. leave the full screen as is. change sub nav to white.

**Comment by spacedino** [comment]
like this
![12_preview_desktop](https://user-images.githubusercontent.com/7339798/31522363-44a4f51c-af62-11e7-8f74-f741fadad315.png)

small illustrations:
[preview_modal_device_icons.zip](https://github.com/ampproject/ampstart/files/1380913/preview_modal_device_icons.zip)

**Comment by spacedino** [comment]
- [ ] center icons
![image](https://user-images.githubusercontent.com/7339798/33848342-4129cfaa-de62-11e7-9a27-4d29dd2df153.png)

- [ ] @778px the preview of the template is gone
![image](https://user-images.githubusercontent.com/7339798/33848230-eec64036-de61-11e7-8fbd-ee2c33eea79a.png)

--------------------- NOT LAUNCH BLOCKING BELOW---------------------

- [ ] remove grey line (maybe 1 px?) at the bottom of the window
![image](https://user-images.githubusercontent.com/7339798/33848130-afaaf4fa-de61-11e7-8270-3adba488eee3.png)

- [ ] change desktop icon to match mocks

- [ ] remove white bar on top with shadow - should be flat on the 


- [ ] leave actual header for the site - is this easy? it should match the mock but let me know if its not.

- [ ] it feels like the download button and the X are too far to the right compared to the mock up. can we move it in so its 80px from the right on desktop?

**Comment by camelburrito** [comment]
The lightbox takes over the whole screen, and we cannot have the top bar inside the fullscreen view
