### ISSUE TITLE
[ampstart.com]Browse page - Design 

### ISSUE THREAD

**Issue by camelburrito** [ampproject/ampstart#607]
[ampstart.com]Browse page - Design

**Comment by spacedino** [comment]
![8_templates_9 25 17 copy](https://user-images.githubusercontent.com/7339798/31339554-2807df50-acfb-11e7-8250-70e1e14ad289.png)
![8_templates_redlines copy](https://user-images.githubusercontent.com/7339798/31339555-283eeab8-acfb-11e7-9bea-9d6972b0e6cb.png)
![12_preview_desktop copy](https://user-images.githubusercontent.com/7339798/31339569-33001602-acfb-11e7-96c4-4e9880550311.png)
