### ISSUE TITLE
[ampstart.com] Home page update V2 - design

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#608]

**Comment by spacedino** [comment]
![12_preview_desktop copy](https://user-images.githubusercontent.com/7339798/31339835-18f88c7a-acfc-11e7-9e0d-0e28990707f9.png)
![13_homepage_hero_loader copy](https://user-images.githubusercontent.com/7339798/31339840-1d5063e2-acfc-11e7-8f43-c880733b9f10.png)

![_homepage_interaction_spex_new](https://user-images.githubusercontent.com/7339798/31339825-11f03a36-acfc-11e7-9b9e-d8f31f5442d1.png)
![1h_homepage_interaction_9 25 17 copy](https://user-images.githubusercontent.com/7339798/31339827-11f2a1fe-acfc-11e7-957a-7fb493493e84.png)

**Comment by spacedino** [comment]
assets

![0_home_hero_loader](https://user-images.githubusercontent.com/7339798/31339898-495d3294-acfc-11e7-95a9-d82287e9aa92.png)
![Uploading 1_home_hero_image.png…]()
![2_scenic - both](https://user-images.githubusercontent.com/7339798/31339897-495cf568-acfc-11e7-864f-897cc2144c8a.png)
![Uploading 2A_scenic 2.png…]()
![Uploading 2B_scenic 1.png…]()
![Uploading 3_lune - both.png…]()
![Uploading 3A_lune_desktop.png…]()
![Uploading 3B_lune_mobile.png…]()
![Uploading 4_bikes_both.png…]()
![Uploading 4A_bikes.png…]()
![Uploading 4B_bikes.png…]()
![Uploading component 1.png…]()
![Uploading component 2.png…]()
![Uploading component 3.png…]()
![Uploading component 4.png…]()
![Uploading component 5.png…]()
![Uploading component 6.png…]()
![Uploading component 7.png…]()
![Uploading component 8.png…]()
![Uploading component 9.png…]()

**Comment by spacedino** [comment]
![lune_710x955](https://user-images.githubusercontent.com/7339798/31523135-a7d4fb2e-af66-11e7-820f-be896fb182cc.png)
![the_scenic_710x955](https://user-images.githubusercontent.com/7339798/31523136-a9c883ec-af66-11e7-91fc-d307e2ed1b31.png)
![bike_shed_710x955](https://user-images.githubusercontent.com/7339798/31523138-acc6e96c-af66-11e7-8468-1af969e6bb07.png)

**Comment by spacedino** [comment]
new lune image

![lune_710x955](https://user-images.githubusercontent.com/7339798/31523509-cae4d128-af68-11e7-9f1d-fb7c5405c1be.png)

**Comment by camelburrito** [comment]
Fixed
