### ISSUE TITLE
[ampstart.com] BUG - missing new footer

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#633]
![image](https://user-images.githubusercontent.com/7339798/31340538-62bf6a8e-acfe-11e7-9542-d7cb5feb6b7f.png)

**Comment by camelburrito** [comment]
@spacedino - responsive spec for this across different screen sizes?

**Comment by spacedino** [comment]
redlines here:

![footer_mobile_redlines](https://user-images.githubusercontent.com/7339798/32915669-82f95bd2-cace-11e7-8a17-7ee1948962f8.png)
![footer_tablet_redlines](https://user-images.githubusercontent.com/7339798/32915674-86a2e32a-cace-11e7-9cfe-044c367de181.png)
![footer_1000px_redlines](https://user-images.githubusercontent.com/7339798/32915677-8977fe3c-cace-11e7-93e9-6bcc0c4b9b83.png)


![footer_mobile](https://user-images.githubusercontent.com/7339798/32915680-8dd0a98e-cace-11e7-8a06-d9b74169be5a.png)
![footer_tablet](https://user-images.githubusercontent.com/7339798/32915686-95865778-cace-11e7-9fb4-d96743716b25.png)
![footer_1000px](https://user-images.githubusercontent.com/7339798/32915693-9bfc335c-cace-11e7-837f-7b827a336fb8.png)
