### ISSUE TITLE
[ampstart.com] BUG - TEMPLATES page: Replace bikes image

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#635]
with this one.
![templates_bikes_360x640](https://user-images.githubusercontent.com/7339798/31341033-094a9012-ad00-11e7-85d6-61f61674fed8.png)

**Comment by camelburrito** [comment]
need the exact image with same aspect ratios. (it would be better if you can replace this at source)

**Comment by spacedino** [comment]
see above, its here :)
