### ISSUE TITLE
Headlines touches edges of the screen

### ISSUE THREAD

**Issue by cramforce** [ampproject/ampstart#644]
The AMP Start homepage looks really bad on a phone, because the text goes right to the edges of the screen. A little bit of padding would fix it.

![screenshot_20171007-122423](https://user-images.githubusercontent.com/89679/31349218-32b0f10e-acd7-11e7-88c7-d3f79bcdcf5f.png)

**Comment by camelburrito** [comment]
@cramforce - we are releasing a new home page in 2 days - That should fix it.
