### ISSUE TITLE
[ampstart.com] BUG - Bike Shop - blank space on Products page

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#647]
**Current:**
User scrolls down Products page > end of products > blank space > reaches the footer

![image](https://user-images.githubusercontent.com/7339798/31470754-3e8c667e-ae9a-11e7-811b-a76695a3f347.png)
![image](https://user-images.githubusercontent.com/7339798/31470830-9fdb9ee0-ae9a-11e7-83bd-5dbecfeee4f6.png)

**Should be:**
User scrolls down Products page > end of products > reaches the footer

**Comment by camelburrito** [comment]
Fixed
