### ISSUE TITLE
[ampstart.com] BUG - Bike Template - all pages should load in preview mode

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#653]
**Current**
User clicks on PREVIEW mode > user is in PREVIEW mode browsing Bike Template > use clicks sidebar > Products > and chooses a product > Product Detail Page opens in a new tab

**Should be**
User clicks on PREVIEW mode > user is in PREVIEW mode browsing Bike Template > use clicks sidebar > Products > and chooses a product > Product Detail Page opens in THE IFRAME.

I'm not sure why this is happening. It seems to be happening for every size device. Didn't notice this before...

**Comment by camelburrito** [comment]
This is because of AMP runtime sanitizing the HTML , cant be fixed now

**Comment by camelburrito** [comment]
This is not feasible for now - closing
