### ISSUE TITLE
[ampstart.com] BUG - Home - Github seciont has odd text ragging (mobile) (not launch blocker)

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#662]
Should be:
Make the cards wider on mobile so it reads:
Read the documentation /
or request a feature on Github.

![image](https://user-images.githubusercontent.com/7339798/31554902-f21d27aa-aff3-11e7-8d3b-752cb2325d39.png)

**Comment by camelburrito** [comment]
This seems to be fixed.
