### ISSUE TITLE
Radio buttons: fill-in is off-center

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#67]
The off-center fill-in for the selected radio buttons gives them a kind of googly-eye look:

<img width="421" alt="screen shot 2017-02-20 at 3 13 55 pm" src="https://cloud.githubusercontent.com/assets/16807766/23144840/486bfc7c-f77f-11e6-9616-5449cba55d83.png">

Is it possible to center the fill-in?

/to @camelburrito  /cc @abeck000

**Comment by camelburrito** [comment]
Fixed
