### ISSUE TITLE
Clicking on product takes you into new tab (and outside preview mode)

### ISSUE THREAD

**Issue by rudygalfi** [ampproject/ampstart#681]
When in preview mode on this page, when I click on "Horn handles" I'm taken to https://ampstart-iframes.firebaseapp.com/templates/e-commerce/product-details.amp

<img width="748" alt="screen shot 2017-10-19 at 11 30 17" src="https://user-images.githubusercontent.com/3888212/31787570-07e1a65c-b4c1-11e7-8b4a-36d9644f8822.png">

**Comment by camelburrito** [comment]
This is a side effect of amp-list and there is no way out
