### ISSUE TITLE
When inside Sidebar ampstart-nav-item, ampstart-input lost focus one second after clicking it

### ISSUE THREAD

**Issue by apraditya** [ampproject/ampstart#684]
I was trying to put a search form in AMPStart sidebar, the text input lost focus a second after clicking it. Here's how to reproduce it:

- Copied from the navigation component,
- include the `amp-form` js,
- then simply add the search form like:

```html
        <li class="ampstart-nav-item ">
          <form role="search" action="/articles.amp" accept-charset="UTF-8" method="get" novalidate="" target="_top" class="i-amphtml-form" _lpchecked="1">
            <input name="utf8" type="hidden" value="✓">
            <div class="ampstart-input inline-block relative m0 p0 mb3">
              <input type="text" name="q" id="ip1" class="block border-none p0 m0 user-valid valid" placeholder="Search">
              <label class="absolute top-0 right-0 bottom-0 left-0" for="ip1">Search</label>
            </div>
            <button class="ampstart-btn">
              <span class="fa fa-search"></span>
            </button>
          </form>
        </li>
```

It works if I put the exact snippet above into the navbar and there was no error in the browser console so I thought I'd file a bug here. For more visual, see the [codepen](https://codepen.io/apraditya/pen/eGXaRV) on a smaller HTML preview.

**Comment by camelburrito** [comment]
is this on a particular browser? i tried on Max Os Latest chrome and it seems to be file

**Comment by camelburrito** [comment]
@apraditya - I am closing this for now , feel free to re-open with more platform specifics
