### ISSUE TITLE
[Gallery - Home] Content changes for tags

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#706]
- [ ] Replace "A reappropriation of violence / Janet Lande" with "Palm Tree Dreams"
- [ ] Should we change any of the other ones? "No name" > "Untitled" ? @ericlindley-g @mattludwig

**Comment by mattludwig** [comment]
I'd also add:

"Breakfast of Champions" >> "Swimming in Neon"
"Flying Pigs" >> "Flower Still Life"
"Angry Mushroom Cloud" >> "The Way Out"
"Exit" >> "Flora and Illuminations"
"Broken Carton" >> "Spiraling Industry"
"Self Portrait" >> "Upward Perspective"

I think the others are fine.

**Comment by ericlindley-g** [comment]
all SGTM—thanks!
