### ISSUE TITLE
[Gallery - Sidebar] The avatar and > are misaligned

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#710]
**Current**
The section for "5 Geo Breakfast / Terra Morales" sticks out farther to the left and the > gets cut off by the side bar.

![img_98431](https://user-images.githubusercontent.com/7339798/32255118-f592add8-be62-11e7-9bdc-c9d7b5f5fe56.jpg)

**Should be**
All sections and spacing should match. Ideally the > 's and avatars will be left aligned to accommodate for different text lengths. 

We could either shorten the text or make sure the margin is responsive for the sidebar container. @camelburrito what do you think is the best way to fix this?

**Comment by bentranter** [comment]
This is caused by the rule,

```css
amp-sidebar {
  ...
  max-width: 80vw!important;
  ...
}
```

in the Sidebar components stylesheet. I don't think I can override this, so we could either decrease the left margin, make the text smaller/shorter, or some other workaround.

**Comment by camelburrito** [comment]
make the sidebar content box and add padding should get you there.

**Comment by bentranter** [comment]
Cool, I'll try that
