### ISSUE TITLE
[Gallery - Exhibit Page] The images at the bottom should have parallax

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#711]
**Current:**
Images below are stacked and move together as one chunk. This means they are not viewable really.
![img_98361](https://user-images.githubusercontent.com/7339798/32255293-0ce67c5c-be64-11e7-8ba7-f555e1f45550.jpg)

**Should be:**
We should be using parallax here. If we can't yet, then lets space out the images so they are not overlapping. If we can, lets fix it to match the initial intention.

**Comment by bentranter** [comment]
Parallax doesn't work unfortunately, but we can space the images out more.

**Comment by camelburrito** [comment]
@bentranter - why does parallax not work ? 

Did you try this?
https://www.ampproject.org/docs/reference/components/amp-position-observer

Check out the 6 codepen examples if you need help.

**Comment by davidtapp** [comment]
@camelburrito Our previous parallax build had to go without AMP component usage, as it still had a few too many kinks to work out at the time. Thus we collectively decided to remove it. This request unfortunately will require too much additional net new effort to work we can't accommodate for.

**Comment by camelburrito** [comment]
@davidtapp - I see ok - Ill leave it up to @ericlindley-g and @mattludwig

**Comment by spacedino** [comment]
@davidtapp - the request in this ticket was to "space out the images so they are not overlapping." Do you know why they are still overlapping? Was that an intentional design?...It still looks a bit off on mobile....thanks!

**Comment by ksokhan** [comment]
Hey @spacedino heres the original design (please ignore different images). The intention was to actually have a bit of overlap. I would say it looks about right now after @bentranter's adjustments. https://www.dropbox.com/s/f9mq1e0jdvyoaw1/Screenshot%202017-11-17%2016.04.29.png?dl=0

**Comment by spacedino** [comment]
ok! lets leave it :) thanks.
