### ISSUE TITLE
[Gallery - Exhibit Page] Exhibits section on mobile is misaligned

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#712]
**Current:**
Exhbits section on mobile is misaligned and looks off and the images are too small. 

![img_98441](https://user-images.githubusercontent.com/7339798/32294775-73df634c-bf04-11e7-8d44-807c4e996ab2.jpg)

**Should be:**
The previous design has the images more horizontally centered. They should also be a little bigger on mobile to fill the space better.

**Comment by camelburrito** [comment]
on ipad and ipad mini (chrome emulator) dimensions the big pineapple image is not aligned in the middle.

**Comment by davidtapp** [comment]
Kinda by design. Will center all images.

**Comment by camelburrito** [comment]
I think it’s just the big pineapple that looks odd on tablet widths , I’ll leave it up to @spacedino
