### ISSUE TITLE
[Gallery - Exhibit page]

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#713]
**Current**
Entire exhibit page moves horizontally even though there is only a slider at the top. It makes the rest of the page look a little off. 

![img_98311](https://user-images.githubusercontent.com/7339798/32255510-a7895260-be65-11e7-9607-d9d8b6148958.jpg)

**Should be**
Can we restrict this for the rest of the page? Is this because of the carousel at the top?

**Comment by camelburrito** [comment]
This is still not fixed. I debugged this issue for you - 

<svg class="gallery-inner-background-2 block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1167 599" aria-hidden="true"><path d="M8 359.5c0 143.5 56.5 179 177.5 179s150.054-30 286-30S737 594 879.5 594 1159 543.5 1159 299.5 1062.734 5 902 5C741.266 5 689 220 568 220s-333.383-72.5-425-72.5c-91.617 0-135 68.5-135 212z" fill="#f5f6fd"></path></svg>


This is what is causing the page to scroll, I guess may be setting this as a background image to the carousel (and adding a bit of padding on the carousel would help your case.)

**Comment by davidtapp** [comment]
@camelburrito can you let us know where you're seeing this (browser etc)? We're having trouble reproducing it and think we caught it in most browsers.

**Comment by camelburrito** [comment]
iPhone safari

**Comment by bentranter** [comment]
Sorry @camelburrito, I think I'll need a specific iOS version to repro this 😞 tried on iOS Safari 11.1.2 on iPhone 6+, and I don't observe the issue.

**Comment by camelburrito** [comment]
I used iphone 6s and 11.0.3
