### ISSUE TITLE
[Gallery - Exhibit Page] @1,000px width the arrows for next get wonky

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#717]
No idea why this is happening...
![image](https://user-images.githubusercontent.com/7339798/32256213-f9679f4c-be6a-11e7-96ee-a6447360da02.png)

**Comment by icidasset** [comment]
Hi @spacedino 👋 
What do you mean by "wonky", I'm not seeing anything wrong?

**Comment by spacedino** [comment]
(Cant repo, think it was my graphics card! :) )
