### ISSUE TITLE
[Gallery - Photos] They still look too low res

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#719]
Photos don't look high res.

**Comment by icidasset** [comment]
Do you still have this issue @spacedino?
Or do we need @3x sized assets?

**Comment by camelburrito** [comment]
make the 2x images bigger and use a png optimizer, i usually try to have 2x somewhere around 1024 x 768

**Comment by camelburrito** [comment]
if the default images are too small make the current 2x the default. Using a png optimizer should help you bring down the file sizes.
