### ISSUE TITLE
[Land and See - Home] Images in hero carousel should span the width of the page.

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#721]
**Current**
For viewports bigger than > 1,025 px wide, the hero carouse looks broken. For viewports < 1,023, we don't show the other two slides. 
![image](https://user-images.githubusercontent.com/7339798/32340165-0a7a8f90-bfb7-11e7-88eb-12d060e35391.png)

**Should be**
I like having the slides show on the sides if we can always have it span the width of the viewport. Otherwise we might just want to have the hero image span the width of the viewport. cc @ericlindley-g @camelburrito @mattludwig
![image](https://user-images.githubusercontent.com/7339798/32340410-c44a6210-bfb7-11e7-857c-bc2a9fb17c34.png)

**Comment by afilbert** [comment]
This closely follows the approved design mocks. I think the intention was to showcase multi-`amp-carousel` communication using `amp-bind`. The widths needed to be fixed in order to render the absolutely positioned carousels without confusing AMP Runtime's or the `amp-carousel`'s initial dimensions.

**Comment by spacedino** [comment]
The approved design mocks were 1002px wide. I didn't see any mock ups that were bigger showcasing what what implemented in its entirety. I know that's the challenge with approving statci mocks. If the intention was NOT to span the entire viewport width that wasn't explicitly communicated to me. Apologies if I misunderstood. We do need to fix this before we launch, but I understand if your team doesn't have the bandwith. Again, apolgies for any confusion. This was the approved design mock. @camelburrito can you fix this easily? Do you need to ask any questions about this before hand?

![image](https://user-images.githubusercontent.com/7339798/33047673-cf205c82-ce0b-11e7-80a5-f8ae3e28b1e4.png)


cc/ @mattludwig @ericlindley-g

**Comment by spacedino** [comment]
@camelburrito maybe an easy fix due to the eng constraints are to just show more of the images on the side vs expanding the size of the carousel. I know we've had issues with fixed width base on viewport but maybe we can come up with something clever here. I just want it to look intentional, whatever we do.

**Comment by spacedino** [comment]
per conversation: suggested fixes for G&M to adjust as needed
- [ ] increase max width to 1600px
- [ ] feather out edges per image below

![image](https://user-images.githubusercontent.com/7339798/33461817-0381b0a4-d5e9-11e7-9122-4cd385ccfc20.png)
