### ISSUE TITLE
[Land and See - Home] Text is too hard to read on Hero Carousel

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#722]
**Current**
Text is too small and too light.
![image](https://user-images.githubusercontent.com/7339798/32341676-6829bf04-bfbb-11e7-8fda-913d2c041f7f.png)

**Should be**
1.25 rem size / 1.25 line height ; .85 Opactiy
![image](https://user-images.githubusercontent.com/7339798/32341902-0e255a9e-bfbc-11e7-9599-bacd57017498.png)

**Comment by afilbert** [comment]
I can increase the opacity, as I made a development decision to try and achieve a semi-bold look where the web fonts failed to cooperate consistently. The sizing, however, closely follows the approved [mocks](https://github.com/ampproject/ampstart/tree/master/mocks/land-see).

**Comment by spacedino** [comment]
Design mocks @1024px width - 
![image](https://user-images.githubusercontent.com/7339798/33048690-0fb07a02-ce11-11e7-8ccb-4226d1304d99.png)


Actual @1024px width - 

![image](https://user-images.githubusercontent.com/7339798/33048717-2ac1f23a-ce11-11e7-958f-2eeded7261d4.png)

The sizing is close but does look a little bigger in the mock ups proportionally. I totally get that you want to follow what was intended. I think I actually misread the mockups and was scaling them up in my browser because I thought they were scaled down. I didn't realize the whole time that was for 1024px wide, I should have clarified. In any event, ideally you could make the changes if its easy and quick (the line height is definitely larger in the mock up) and if not we can just adjust it on our end. So feel free to disregard if you don't have the bandwith. Thanks!!

cc @mattludwig @ericlindley-g @camelburrito

**Comment by spacedino** [comment]
lets see if we can change this in variables.

**Comment by camelburrito** [comment]
No this has to be individually changed
