### ISSUE TITLE
[Gallery - Exhibit Page] Update location on map at page bottom

### ISSUE THREAD

**Issue by mattludwig** [ampproject/ampstart#724]
Should we change the map at the page bottom to have a red location dot somewhere other than the Google HQ? @spacedino @ericlindley-g

**Comment by mattludwig** [comment]
FYI - I don't believe I have access to assign or put this issue in the Metalab project.

**Comment by ericlindley-g** [comment]
+1   and /cc @camelburrito on the GitHub access issue

**Comment by davidtapp** [comment]
Will do this one. Changing it to the Met! 1000 5th Ave, New York, NY 10028, USA
