### ISSUE TITLE
[Land and See - Subscribe module] Change text

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#726]
**Current**
Text is confusing - doesn't set expectations for what the user should enter into the field. Also the text is not the right font. The caps are hard to read. 

![image](https://user-images.githubusercontent.com/7339798/32343692-9e1cf2d8-bfc1-11e7-8c09-ea4ada397c85.png)

**Should be**

- [ ] Something like this: Weekly inspiration delivered to your inbox from Land and See. Enter your email. 
- [ ] Font looks like it should be Crimson
- [ ] Change to lower case

![image](https://user-images.githubusercontent.com/7339798/32343572-2dd04d68-bfc1-11e7-8a2b-f3fc132681a6.png)
![image](https://user-images.githubusercontent.com/7339798/32343659-7f13f648-bfc1-11e7-8b77-fcd7045c2163.png)

**Comment by afilbert** [comment]
Nice catch on `Crimson Text` being overridden. #698 may have introduced that.

**Comment by afilbert** [comment]
The styles and verbiage of the subscription footer section do closely follow the approved [mocks](https://github.com/ampproject/ampstart/tree/master/mocks/land-see).

**Comment by spacedino** [comment]
@mattludwig @ericlindley-g - does this new copy work? i've been seeing our templates more and more in the wild now and people really don't change things they think are good enough. I fear this will be one of them and want to make sure what we put here is what we would recommend from a copy perspective as well. This is similar to what I have see in the wild, so just explaining a bit more I think would be nice. Setting the user expectation as to what they are subscribing too, esp because its an email field. 

lmk what you think.

**Comment by ericlindley-g** [comment]
+1 to clarifying that this is an email signup—though I think we can be really economical here and still be clear. I suggest:

Text above input: "Weekly inspiration from Land + See"
Placeholder text for input: "Enter email address to subscribe"

WDYT?

**Comment by mattludwig** [comment]
SGTM!
