### ISSUE TITLE
[Land and See - Subscribe module] Arrow button (submit) sends user to ampstart.com

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#729]
**Current**
User clicks subscribe button and is taken to ampstart.com
![landandsee_subscribe](https://user-images.githubusercontent.com/7339798/32344059-c36f1c5e-bfc2-11e7-853d-3beb60f487a8.gif)

**Should be**
Not sure...it probably shouldn't go anywhere. @ericlindley-g @mattludwig @camelburrito

**Comment by ericlindley-g** [comment]
+1 to not going anywhere for now  (Feature enhancement for later would be to display text below that says "Subscribed" — or error message in the event of an error.  If this is trivial to do could go with it now)

**Comment by afilbert** [comment]
Change form to submit to root should fix this: `/template/land-see/land-see.amp.html`.
