### ISSUE TITLE
[Land and See - Home + Stories page] Anything that looks like an article page should link to the article page

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#731]
**Current**
The only way to navigate to the Article page (Kim Meyong page) is via the Hero Carousel on the Home page. 

![image](https://user-images.githubusercontent.com/7339798/32348128-0db9cfe0-bfd0-11e7-9536-b5fb78e6fdab.png)

**Should be**
Link all images / text that looks like an article to the Article page. Ex: all of the images in the hero carousel, thumbnails should link (see below), article titles should link (see below), any thing that is an article summary / preview.

If we want to have 1 carouse dedicated to the Stories section and link there that would be OK with me. 

![image](https://user-images.githubusercontent.com/7339798/32348164-2c3a79e2-bfd0-11e7-8ecb-95713f5ff4b4.png)
![image](https://user-images.githubusercontent.com/7339798/32348216-4cf5a58a-bfd0-11e7-8a5c-5a48055fd362.png)
![image](https://user-images.githubusercontent.com/7339798/32348222-5486199c-bfd0-11e7-814a-980db43adae4.png)
![image](https://user-images.githubusercontent.com/7339798/32348239-60729a28-bfd0-11e7-80e7-39ba145d8d50.png)

**Comment by afilbert** [comment]
Thanks for the feedback, @spacedino. Will it suffice to link all story links back to the completed Kim Myeong story page?
