### ISSUE TITLE
[Land and See - Article Page] Change block quote attribution from "New York Times" > "Dorian Grey"

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#732]
**Current**
I think we shouldn't mention any other news publications if we can help it. I realize this is probably really small but I just don't want to run into issues where we might be misrepresenting a brand, esp bc its not a real quote and if we were we would need to credit the author as well.
![image](https://user-images.githubusercontent.com/7339798/32348436-f7f2c6c0-bfd0-11e7-83bc-edcf97da4bce.png)

**Should be**
"Dorian Grey". cc @mattludwig @ericlindley-g

**Comment by ericlindley-g** [comment]
+1  Agreed that we shouldn't mention any brands in the templates to the extent possible (i.e. when not already baked into an embed like twitter or instagram
