### ISSUE TITLE
[Land and See - Carousels] Carousel transitions on Home and Article page are a little sticky

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#734]
**Current**
The transition feels too fast and a little sticky. On mobile the snapping feels sticky and too fast as well. 
![landandsee_hero_carousel](https://user-images.githubusercontent.com/7339798/32348686-cd1c594c-bfd1-11e7-86a4-fba3b754cada.gif)

For some reason the carousel on the Article Page is slow on desktop but I don't know if other people can repro...
![landandsee_article_page](https://user-images.githubusercontent.com/7339798/32351710-90eb2b38-bfdb-11e7-91ab-f73f5d580975.gif)

**Should be**
Can we slow it down by .5 seconds and make the transition a bit smoother?

**Comment by spacedino** [comment]
we might need to fix the component for this one... amp-carousel , type=slides

**Comment by camelburrito** [comment]
This is not in ampstart's control. I have made a few fixes on the amp-carousel as well. Lets revisit this on amphtml if needed
