### ISSUE TITLE
[Land and See] Tap targets are too small of Menu, X, and <>'s on mobile

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#737]
**Current**
Tap targets are too small to consistently hit every time.

**Should be**
All tap targets should be a min of 40px40px around the icon. For the carousel images, if a user taps the 30% to the right and 30% to the left can we trigger the advance in that direction?

**Comment by afilbert** [comment]
Thanks for the direction. Will address in my next PR.

**Comment by afilbert** [comment]
Ok, I addressed the tap target to be 40px/40px. The 30% might be a good suggestion for future `amp-carousel` enhancements.

**Comment by spacedino** [comment]
@afilbert thank you! yea that's a really good idea - we should just bake that in.
