### ISSUE TITLE
[Land and see - Home + Stories] Horizontal scrolling is enabled even though there is nothing there

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#739]
**Current**
User can move the whole page over to the left because the pink triangle is showing the full image. 
![img_98561](https://user-images.githubusercontent.com/7339798/32352271-b5a65932-bfdd-11e7-92da-ff16cca91b6f.jpg)

**Should be**
User should not be able to scroll past the content and should be cut off just like the green triangle. 
![image-11 1](https://user-images.githubusercontent.com/7339798/32352333-106256be-bfde-11e7-91b3-edd3fa2a2538.jpg)

**Comment by afilbert** [comment]
This is a known issue on Safari, as documented on the PR: https://github.com/ampproject/ampstart/pull/615

**Comment by spacedino** [comment]
thanks! when #615 is fixed this one will be too. closing for now ( @camelburrito let me know if that's not true).
