### ISSUE TITLE
[Land and See - Home] Random green triangle on mobile

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#741]
**Current**
There is a tiny green triangle that scrolls over some of the content when users scrolls up. Right now on Mobile it looks like a "Scroll to top" icon.
![img_98551](https://user-images.githubusercontent.com/7339798/32352674-6e2952ba-bfdf-11e7-8919-27eb8c8c44c0.jpg)

**Should be**
I think we can just remove it. It's a cool accent but I think the bigger triangles that go behind are better. It gets lost on desktop and looks like a mistake on mobile. Or, we could make it a "scroll to top".... :) @camelburrito @ericlindley-g @mattludwig

**Comment by afilbert** [comment]
Good suggestion, will remove in next PR.
