### ISSUE TITLE
[Land and See - Home] Hero carousel images should link to Article page

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#742]
**Current**
On Mobile or Desktop, if you click anywhere on the carousel image that is not the link or arrows, the page does nothing.

![image](https://user-images.githubusercontent.com/7339798/32352891-5fcf73d8-bfe0-11e7-929e-7ba850ccc2f1.png)

**Should be**
On Mobile or Desktop, if you click on the carousel images / text, you should go to the Article page.

**Comment by afilbert** [comment]
I think a good middle-ground might be to make the title into a link that goes to the Story, in addition to the READ MORE button. I can put that in my next PR, if that works.

**Comment by afilbert** [comment]
Taking a look at this again, today, and I realized the title is already a link to the story. :)
