### ISSUE TITLE
[Land and See - Home] Popular tag is misaligned for anything smaller than < 814 px

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#743]
**Current**
Popular tag  is left aligned but the images in that section move and it looks off at different viewport sizes.

![image](https://user-images.githubusercontent.com/7339798/32352990-c98d0c90-bfe0-11e7-8680-0f9ff3e31a21.png)

**Should be**
Popular tag adjusts with content to left align with content (or something else that looks better).

**Comment by afilbert** [comment]
This does deviate from the approved design [mocks](https://github.com/ampproject/ampstart/tree/master/mocks/land-see), and was a compromise based on how the content came together. May need to manually set width of container to follow the list's breakpoints, as setting to `inline-block`, `table`, or `left` floating the parent container element to auto-resize with child contents seems to obscure the `amp-list`/`amp-carousel` content. Can add to #748 when ready, or create a new PR.
