### ISSUE TITLE
[Land and see - Stries] "Previous" and "next" buttons should take user to the top of the page to continue browsing

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#746]
**Current**
Its awkward when the user is taken to the same scroll position on the page if there is no new content. Its also just confusing about what happened.
![landandsee_prev_next](https://user-images.githubusercontent.com/7339798/32353369-62b5dcfc-bfe2-11e7-909a-1bbc3577d5e4.gif)

**Should be**
Take user to top of new content

**Comment by afilbert** [comment]
As mentioned in #728, I'm not sure amphtml provides a function or component that can scroll to top with JavaScript. An alternative would be to try and use `href="#"` with an anchor. It depends on if that can be used in conjunction with `amp-bind`s `on` action.

**Comment by afilbert** [comment]
I took a look at this, with mixed results: https://github.com/ampproject/ampstart/issues/728#issuecomment-341855157

**Comment by spacedino** [comment]
DUPE of #728
