### ISSUE TITLE
[travel] results page is blank on first load

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#753]

**Comment by rachcurrie** [comment]
This is in progress @ericlindley-g, @bentranter is opening a PR shortly for this.

**Comment by camelburrito** [comment]
<img width="2306" alt="screen shot 2017-11-15 at 3 12 34 pm" src="https://user-images.githubusercontent.com/1037311/32865429-f0c4f7d2-ca17-11e7-8a0c-ee09b33747cd.png">

On chrome desktop - page load is blank and when i hit the dropdown (no selection needed), it makes another network call and fills in the data.


Also the dropdown does not close back after selection is done.

**Comment by davidtapp** [comment]
@camelburrito we're not able to reproduce this on our staging site: https://ampstart-staging-metalab.firebaseapp.com/templates/travel/travel.amp

Can you provide us more repro details possibly?

**Comment by camelburrito** [comment]
Looks fine now !
