### ISSUE TITLE
[Gallery] Assets - sketch / proto / etc.

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#763]
We have these in an email they just need to be added here. 

![image](https://user-images.githubusercontent.com/7339798/32817097-e46bbb26-c970-11e7-8615-d92723e33a83.png)

**Comment by davidtapp** [comment]
**Code Repository:**
https://github.com/metalabdesign/ampstart
**Museum Template Site Link:**
https://ampstart-staging-metalab.firebaseapp.com/templates/gallery/gallery.amp
**Museum Template Link (Unconstrained - Live VR):** 
http://google-amp-gallery-vr-demo-12ab3gsbn3gv1.surge.sh/
**Video of VR Experience:**
https://youtu.be/QSLsWIjaJpo
**Page 2 Parallax Reference (MOV):**
https://www.dropbox.com/s/9ysxd5kyda51i6r/Museum-Dektop-Exhibition-Page_v1.0.mov?dl=0
**Sketch Files of Template:**
https://www.dropbox.com/sh/qi4ao139dm1ortx/AAA3WAROS_2FzZQ517CDoovMa?dl=0

cc @camelburrito @spacedino :-D

**Comment by spacedino** [comment]
Thanks! I know this is a silly question but I don't see the source image files anywhere.... :P

**Comment by davidtapp** [comment]
@spacedino image assets are under each project’s `img` directory and within the Sketch files themselves. Does that work for you guys?

**Comment by spacedino** [comment]
GALLERY:

most recent sketch file: https://github.com/ampproject/ampstart/blob/master/mocks/gallery/gallery.sketch

images link: 
https://github.com/ampproject/ampstart/tree/master/img/gallery
