### ISSUE TITLE
[Land and See] Loader - turn off default 3 dot loader

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#765]
Turn off the 3 dot loader can be over written with "no loading" attribute. https://www.ampproject.org/docs/reference/common_attributes#noloading

(The custom loader you have is great so we don't need the default loader. It's too much on slow networks).

ask @camelburrito if you have an issue with this one - he things its an easy and quick fix.

**Comment by afilbert** [comment]
Thanks for the feedback @spacedino, can you clarify which controls the default 3 dot loader should be turned off for?  Is there an ampstart-specific custom loader that you're referring to? cc @camelburrito

#720 looks like it could be a duplicate.

**Comment by camelburrito** [comment]
I think she means you can turn it off in places where you have a placeholder that serves a similar purpose. (gray background on the home page). 

No, there is no ampstart specific custom loader.

**Comment by spacedino** [comment]
yes correct, this is a dupe. sorry will close!

**Comment by spacedino** [comment]
actually @camelburrito , i'm still seeing it in places like here...its particularly confusing because it looks like the carousel UI. @aghassemi - when we change the loader will it apply to components already implement?

<img width="1680" alt="screen shot 2017-11-20 at 4 48 53 pm" src="https://user-images.githubusercontent.com/7339798/33049076-31332fba-ce13-11e7-9140-c0b44593542e.png">

**Comment by camelburrito** [comment]
So the easy fix here is to add the `noloading` attribute on images and carousels all over. And implement a blanket CSS Placeholder and enable the placeholder by just adding `<div placeholder></div>` in the component markup

**Comment by camelburrito** [comment]
@spacedino feel free to reopen

**Comment by aghassemi** [comment]
```
amp-img .amp-active {
display: none; 
}
```

should do it too.
