### ISSUE TITLE
[Travel] Loader - turn off 3 dot loader

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#766]
Turn off the 3 dot loader can be over written with "no loading" attribute. https://www.ampproject.org/docs/reference/common_attributes#noloading

The custom loaders you have are great without the 3 dots.

ask @camelburrito if you have an issue with this one - he things its an easy and quick fix.

**Comment by davidtapp** [comment]
@spacedino @camelburrito Hey team, we're just trying to be hyper focused on the ship blocking bugs that have sprung up post-PRs. We'll put this one in the enhancement bucket we'll probably leave for now based on a need to come to a close on this asap.
