### ISSUE TITLE
[Gallery] Loaders - remove 3 dot loaders

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#767]
Turn off the 3 dot loader can be over written with "no loading" attribute. https://www.ampproject.org/docs/reference/common_attributes#noloading

The custom loaders you have are great without the 3 dots.

ask @camelburrito if you have an issue with this one - he things its an easy and quick fix.

**Comment by davidtapp** [comment]
@spacedino @camelburrito same goes here as per my note on #766.

**Comment by camelburrito** [comment]
Adding the ‘noloading’ attribute should get rid of the 3 dots
