### ISSUE TITLE
McAfee virus blocking

### ISSUE THREAD

**Issue by valtido** [ampproject/ampstart#774]
I tried to download one of your themes and mcafee stopped me saying that there may be virus by downloading this zip file and virus detected. 

Any thoughts on this ?

**Comment by camelburrito** [comment]
@valtido - Thanks for filing the bug!

The file contains HTML and css in a zip file. Does McAfee do it for all the themes or just one theme ? 

Also the entire repo is open source, if you are worried about downloading from ampstart.com you download the project and build it with one command `gulp build` (If you have npm and gulp installed) and the take the zip file from the archives.

OR an easier way is to use the direct urls from the preview iframes and save the page(s) you like, the main drawback is you might not get the unminified CSS file (which is easy to get by pasting your CSS in an online css unminifier/unpacker  )

**Comment by valtido** [comment]
All the templates reported the same thing, and I am pretty sure it contained viruses too, as my computer got the "blue screen of death" (a MS banter intended) shortly after that and computer kept freezing. 

This was really unusually and never happened before that.

I would recommend that someone does a full scan or investigate on the files.

**Comment by camelburrito** [comment]
i just downloaded a couple of zips and virus scanned them. They are fine and have no virus. you must have  caught it up elsewhere. None of our zip files have any executables in them so they should be pretty safe.
