### ISSUE TITLE
[ampstart.com] Footer tweaks

### ISSUE THREAD

**Issue by spacedino** [ampproject/ampstart#776]
footer:

- [x] center share icons
- [x] text explaining amp = .75rem
- [x] 0 LS    
- [x] "other" + "links" - label class
- [x] links size = 1rem
- [x] margin under links .5rem
- [x] add "YouTube Channel" under "other resources"
- [ ] remove extra spacing at the bottom
- [ ] add analytics

cc @ericlindley-g

**Comment by spacedino** [comment]
- [ ] text is too small now, go back to 1rem
- [ ] line height for text should be the same as "body copy" class

**Comment by camelburrito** [comment]
https://github.com/ampproject/ampstart/pull/779
