### ISSUE TITLE
Repository size is enormous

### ISSUE THREAD

**Issue by piotrkochan** [ampproject/ampstart#797]
I think that it is not normal that repository size is about 600MiB

```
$ git clone https://github.com/ampproject/ampstart.git
Cloning into 'ampstart'...
remote: Counting objects: 6530, done.
remote: Compressing objects: 100% (2/2), done.
Receiving objects:  80% (5250/6530), 392.75 MiB | 472.00 KiB/s
```

**Comment by camelburrito** [comment]
This repo is really heavy on images. If you think of it as a place to hold multiple templates (websites) then you will know why it is heavy on size. If you want to work on it locally then it totally makes sense to delete unwanted template data.
