### ISSUE TITLE
Jekyll compliant templates

### ISSUE THREAD

**Issue by rrjanbiah** [ampproject/ampstart#807]
Wishlist: Jekyll compliant templates https://www.ampstart.com/templates would be really cool to have

**Comment by camelburrito** [comment]
Thanks for filing the feature request!

I know some one who created a jekyll theme from our blog post theme - https://github.com/shoyan/ampstart-blog-post. 


We will have this in mind when we do future planning.

**Comment by rrjanbiah** [comment]
@camelburrito Thanks for referring above project

I vaguely remember that @pbakaus was putting lot of efforts to make AMP spread across all communities. Listing these works in main website will be very good.

May I know if I can contribute anything here?
