### ISSUE TITLE
Templates won't load after clearing ampcache

### ISSUE THREAD

**Issue by prasannamestha** [ampproject/ampstart#810]
Hey,

I tried clearing the amp cache using https://amp-cache-refresh.appspot.com/. Now surprisingly the templates listed here https://ampstart-iframes.firebaseapp.com/templates don't load. We can see the preview but upon clicking on the template, blank page loads.

Thanks

**Comment by camelburrito** [comment]
does it permanently not load ? or was it a one time thing? 

I just tried this on incognito works fine for me.
