### ISSUE TITLE
Land+See: instagram embed sizing broken

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#815]
Instagram embed sizing is broken on the article page (overlaps with other UI):

<img width="348" alt="screen shot 2018-04-20 at 8 59 49 am" src="https://user-images.githubusercontent.com/16807766/39061475-42f08dec-4479-11e8-8045-3ecbfcaf6239.png">

Related to resizing rule changes for amp-instagram?
/cc  @cathyxz  @camelburrito

**Comment by ericlindley-g** [comment]
Looks like this happens only in the embedded context, FYI (on desktop ampstart.com, click the eye icon associated with the template to see)

**Comment by camelburrito** [comment]
which page is this on ?

**Comment by ericlindley-g** [comment]
Sorry — not on the home page for Land+See, but on the article page

**Comment by camelburrito** [comment]
This looks like something broke on instagram. We have not touched anything here for a while

**Comment by nainar** [comment]
Assigning this to myself. Seem like instagram isn't returning the height with the compensated padding-{top,bottom} values anymore. We currently compensate for that [here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-instagram/0.1/amp-instagram.js#L216). Removing our compensation fixes the issue. I'll submit a PR for this.

**Comment by nainar** [comment]
PR out here: https://github.com/ampproject/amphtml/pull/15105
