### ISSUE TITLE
Remove Google+ from social icon list examples

### ISSUE THREAD

**Issue by alankent** [ampproject/ampstart#867]
Given the changes in Google Plus focus ("On April 2, 2019, Google+ will be shut down for consumers"), I suggest the "G+" logo be removed from social sharing examples. 

See https://www.ampstart.com/components#links-and-sharing

**Comment by DrewRoberts** [comment]
There are a total of 12 references to gplus that I found: 

- https://github.com/ampproject/ampstart/search?q=gplus&unscoped_q=gplus

I'm working on a pull request to remove them.
