### ISSUE TITLE
Is it possible to make the RESPONSIVE MENUBAR with hoverable dropdown?

### ISSUE THREAD

**Issue by zipswich** [ampproject/ampstart#879]
It is great that this project offers off-the-shelf UI components.

I am wondering if the RESPONSIVE MENUBAR can have hoverable dropdown?

I have been using this [nice pure CSS responsive menu](https://codepen.io/andornagy/pen/RNeydj) for a while.  Unfortunately, it causes the following AMP warning:
"The author stylesheet specified in tag 'style amp-custom' is too long - the limit is 50000 bytes."

I really want to use the ERESPONSIVE MENUBAR of this project.  It would be perfect if it has hoverable dropdown.

**Comment by camelburrito** [comment]
The responsive menu on the link has a lot of outdated css and other bloat , you will be able to implement a hover-able dropdown with a few more lines of css along with what comes with the template. 

You can read through this blog for some ideas on how to get this done. 
https://css-tricks.com/solved-with-css-dropdown-menus/

**Comment by zipswich** [comment]
Thank you. I created another issue #880
